"""
AstroDoncel API — FastAPI backend for e-CALLISTO spectrograms.
Scientific engine ported from e-CALLISTO FITS Analyzer (Sahan S Liyanage, v2.4.1).
"""

from __future__ import annotations

import asyncio
import glob
import html
import logging
import os
import re
import threading
import warnings
from collections import OrderedDict
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from urllib.error import URLError
from urllib.request import Request, urlopen

import numpy as np
from astropy.io import fits
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from scipy.ndimage import label as ndi_label

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="AstroDoncel API", version="0.2.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR_LOCAL = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "data")
)
ECALLISTO_DATA_DIR = os.environ.get(
    "ECALLISTO_DATA_DIR", "/var/services/web/ecallistodata"
)
ETHZ_BASE_URL = "http://soleil.i4ds.ch/solarradio/data/2002-20yy_Callisto"

# Static fallback list — 76 real stations extracted from the ETHZ archive
# (generated by scanning multiple dates from 2024-2026)
_STATIONS_FALLBACK: list[str] = [
    "ALASKA-ANCHORAGE",
    "ALASKA-COHOE",
    "ALASKA-HAARP",
    "ALGERIA-CRAAG",
    "ALMATY",
    "AUSTRALIA-ASSA",
    "AUSTRIA-KRUMBACH",
    "AUSTRIA-MICHELBACH",
    "AUSTRIA-OE3FLB",
    "AUSTRIA-UNIGRAZ",
    "BIR",
    "BRAZIL",
    "CROATIA-VISNJAN",
    "DENMARK",
    "EGYPT-ALEXANDRIA",
    "EGYPT-SPACEAGENCY",
    "ETHIOPIA",
    "FINLAND-KEMPELE",
    "FINLAND-RUISSALO",
    "FINLAND-SIUNTIO",
    "GERMANY-DLR",
    "GERMANY-ESSEN",
    "GLASGOW",
    "GREENLAND",
    "HUMAIN",
    "HURBANOVO",
    "INDIA-GAURI",
    "INDIA-OOTY",
    "INDIA-UDAIPUR",
    "INDONESIA",
    "ITALY-STRASSOLT",
    "JAPAN-IBARAKI",
    "KASI",
    "MALAYSIA-BANTING",
    "MEXART",
    "MEXICO-ENSENADA-UNAM",
    "MEXICO-FCFM-UANL",
    "MEXICO-FCFM-UNACH",
    "MEXICO-LANCE",
    "MEXICO-LANCE-A",
    "MEXICO-LANCE-B",
    "MEXICO-UANL-INFIERNILLO",
    "MONGOLIA-UB",
    "MRO",
    "MRT1",
    "NASA-GSFC",
    "NORWAY-EGERSUND",
    "NORWAY-NY-AALESUND",
    "NORWAY-RANDABERG",
    "NZ-WAIRAKEI-DLR",
    "PARAGUAY",
    "POLAND-BALDY",
    "POLAND-GROTNIKI",
    "ROMANIA",
    "ROSWELL-NM",
    "RWANDA",
    "SPAIN-PERALEJOS",
    "SPAIN-SIGUENZA",
    "SRI-LANKA",
    "SSRT",
    "SWISS-BLEN5M-E",
    "SWISS-CALU",
    "SWISS-FM",
    "SWISS-HB9SCT",
    "SWISS-HEITERSWIL",
    "SWISS-IRSOL",
    "SWISS-LANDSCHLACHT",
    "SWISS-MUHEN",
    "TAIWAN-NCU",
    "TRIEST",
    "TURKEY",
    "UNAM",
    "URUGUAY",
    "USA-ARIZONA-ERAU",
    "USA-BOSTON",
    "UZBEKISTAN",
]


# ── Models ───────────────────────────────────────────────────────────────────

class SpectrogramResponse(BaseModel):
    station: str
    date: str
    filename: str
    time_axis: list[str]
    freq_axis: list[float]
    z: list[list[float]]
    vmin: float
    vmax: float
    fits_header: dict
    rfi_masked_channels: list[int] = []
    rfi_stats: dict = {}


class CombinedSpectrogramResponse(BaseModel):
    date: str
    layers: list[SpectrogramResponse]
    failed: list[dict]   # [{station, reason}, ...] for stations with no data


class GoesResponse(BaseModel):
    date: str
    available: bool
    reason: str
    times: list[str]
    xrsb: list[float]
    satellite: int | None = None


class StationsResponse(BaseModel):
    stations: list[str]
    source: str


class FileEntry(BaseModel):
    filename: str
    time: str    # "HH:MM:SS"
    label: str   # display label for the UI


class FilesResponse(BaseModel):
    station: str
    date: str
    files: list[FileEntry]
    source: str  # "local", "ethz", "mixed"


# ── I/O helpers ──────────────────────────────────────────────────────────────

def _open_fits(path: str):
    """Open a FITS file (supports .fit, .fits, .fit.gz, .fits.gz)."""
    try:
        return fits.open(path, memmap=False)
    except Exception as exc:
        logger.error("Failed to open %s: %s", path, exc)
        raise HTTPException(status_code=500, detail=f"Could not open FITS file: {exc}")


def _find_local_fits_file(station: str, date: str) -> str | None:
    """Search ../data/ first by (station + date), then by station only."""
    if not os.path.isdir(DATA_DIR_LOCAL):
        return None
    # Match by station + specific date
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
        date_str = dt.strftime("%Y%m%d")
        for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
            matches = glob.glob(
                os.path.join(DATA_DIR_LOCAL, f"*{station.upper()}*{date_str}*{ext}")
            )
            if matches:
                return sorted(matches)[0]
    except ValueError:
        pass
    # Match by station only (useful in development with sample files)
    for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
        matches = glob.glob(os.path.join(DATA_DIR_LOCAL, f"*{station.upper()}*{ext}"))
        if matches:
            return sorted(matches)[0]
    return None


def _find_nas_fits_file(station: str, date: str) -> str | None:
    """Search NAS structure at ECALLISTO_DATA_DIR/YYYY/MM/DD/."""
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return None
    date_dir = os.path.join(
        ECALLISTO_DATA_DIR, dt.strftime("%Y"), dt.strftime("%m"), dt.strftime("%d")
    )
    if not os.path.isdir(date_dir):
        return None
    for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
        matches = glob.glob(os.path.join(date_dir, f"*{station.upper()}*{ext}"))
        if matches:
            return sorted(matches)[0]
    return None


def _time_from_filename(filename: str) -> str:
    """Extract start time as HH:MM:SS from a CALLISTO filename.

    Handles all naming variants: with or without the trailing _NN segment,
    and both .fit / .fits / .fit.gz / .fits.gz extensions.
    """
    m = re.search(r'_\d{8}_(\d{2})(\d{2})(\d{2})', filename)
    if m:
        return f"{m.group(1)}:{m.group(2)}:{m.group(3)}"
    return "??:??:??"


def _list_local_fits_files(station: str, date: str) -> list[str]:
    """Return locally cached filenames for the given station/date."""
    if not os.path.isdir(DATA_DIR_LOCAL):
        return []
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
        date_str = dt.strftime("%Y%m%d")
    except ValueError:
        return []
    found: list[str] = []
    for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
        for path in glob.glob(
            os.path.join(DATA_DIR_LOCAL, f"*{station.upper()}*{date_str}*{ext}")
        ):
            found.append(os.path.basename(path))
    return sorted(set(found))


def _list_ethz_files(station: str, date: str) -> list[str]:
    """Scan the ETHZ HTTP index and return available filenames."""
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return []
    dir_url = f"{ETHZ_BASE_URL}/{dt.strftime('%Y/%m/%d')}/"
    try:
        req = Request(dir_url, headers={"User-Agent": "AstroDoncel/1.0"})
        with urlopen(req, timeout=15) as resp:
            page = resp.read().decode("utf-8", errors="replace")
    except Exception:
        return []
    date_str = dt.strftime("%Y%m%d")
    # Permissive: matches with or without trailing _NN, and .fit/.fits/.fit.gz/.fits.gz
    prefix_re = re.compile(
        r'href="(' + re.escape(station.upper()) + r'_' + date_str + r'_\d{6}.*?\.fits?(?:\.gz)?)"',
        re.IGNORECASE,
    )
    matches = sorted(set(prefix_re.findall(page)))
    if not matches:
        all_files = re.findall(r'href="([^"]+\.fits?(?:\.gz)?)"', page, re.IGNORECASE)
        matches = sorted(c for c in all_files if station.upper() in html.unescape(c).upper())
    return matches


def _download_from_ethz(station: str, date: str, filename: str | None = None) -> str | None:
    """Download a FITS file from the ETHZ archive.

    If `filename` is given, downloads that specific file.
    Otherwise, downloads the first file matching station/date.
    Saves to DATA_DIR_LOCAL for reuse in future calls.
    """
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return None

    dir_url = f"{ETHZ_BASE_URL}/{dt.strftime('%Y/%m/%d')}/"
    os.makedirs(DATA_DIR_LOCAL, exist_ok=True)

    if filename:
        local_path = os.path.join(DATA_DIR_LOCAL, filename)
        if os.path.isfile(local_path):
            logger.info("File already cached: %s", local_path)
            return local_path
        file_url = dir_url + filename
        logger.info("Downloading %s → %s", file_url, local_path)
        try:
            req = Request(file_url, headers={"User-Agent": "AstroDoncel/1.0"})
            with urlopen(req, timeout=120) as resp:
                with open(local_path, "wb") as fh:
                    while chunk := resp.read(512 * 1024):
                        fh.write(chunk)
            logger.info("Download complete (%d bytes)", os.path.getsize(local_path))
            return local_path
        except Exception as exc:
            logger.error("Failed to download %s: %s", file_url, exc)
            try:
                os.remove(local_path)
            except OSError:
                pass
            return None

    # No filename: inspect the directory to find the first matching file
    logger.info("Querying ETHZ archive: %s", dir_url)
    try:
        req = Request(dir_url, headers={"User-Agent": "AstroDoncel/1.0"})
        with urlopen(req, timeout=15) as resp:
            page = resp.read().decode("utf-8", errors="replace")
    except URLError as exc:
        logger.warning("Could not reach ETHZ archive: %s", exc)
        return None

    date_str = dt.strftime("%Y%m%d")
    # Permissive: matches with or without trailing _NN, and .fit/.fits/.fit.gz/.fits.gz
    prefix_re = re.compile(
        r'href="(' + re.escape(station.upper()) + r'_' + date_str + r'_\d{6}.*?\.fits?(?:\.gz)?)"',
        re.IGNORECASE,
    )
    matches = sorted(set(prefix_re.findall(page)))
    if not matches:
        all_files = re.findall(r'href="([^"]+\.fits?(?:\.gz)?)"', page, re.IGNORECASE)
        matches = sorted(c for c in all_files if station.upper() in html.unescape(c).upper())
    if not matches:
        logger.warning("No files for '%s' in ETHZ on %s", station, date)
        return None

    return _download_from_ethz(station, date, filename=matches[0])


# ── FITS loading (ported from fits_io.load_callisto_fits by Sahan) ───────────

def _get_col_1d(table, *names: str) -> np.ndarray | None:
    """Find a column by name (case-insensitive) and return it as a 1D float array."""
    if table is None:
        return None
    col_names = (
        getattr(table, "names", None)
        or getattr(getattr(table, "dtype", None), "names", None)
        or []
    )
    lowered = {str(n).lower(): str(n) for n in col_names}
    for name in names:
        key = lowered.get(name.lower())
        if key is None:
            continue
        try:
            col = table[key]
            arr = np.array(col)
            if arr.ndim == 0:
                continue
            if arr.ndim == 1:
                return arr.astype(float)
            return arr[0].ravel().astype(float)  # repeated table → first row
        except Exception:
            continue
    return None


def _axis_from_header(header, axis_num: int, length: int) -> np.ndarray | None:
    """Reconstruct an axis from WCS keywords (CRVALn, CDELTn, CRPIXn)."""
    try:
        crval = header.get(f"CRVAL{axis_num}")
        cdelt = header.get(f"CDELT{axis_num}")
        crpix = header.get(f"CRPIX{axis_num}", 1.0)
        if crval is None or cdelt is None:
            return None
        i = np.arange(int(length), dtype=float) + 1.0  # FITS is 1-based
        return float(crval) + (i - float(crpix)) * float(cdelt)
    except Exception:
        return None


def _freq_axis_from_range(header, length: int) -> np.ndarray | None:
    """Reconstruct the frequency axis from FREQMIN/FREQMAX header keywords."""
    try:
        lo = header.get("FREQMIN")
        hi = header.get("FREQMAX")
        if lo is None or hi is None:
            return None
        lo, hi = float(lo), float(hi)
        if not (np.isfinite(lo) and np.isfinite(hi)):
            return None
        # CALLISTO: highest frequency in first row → linspace(hi→lo)
        return np.linspace(max(lo, hi), min(lo, hi), int(length), dtype=float)
    except Exception:
        return None


def _load_callisto_data(hdul) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load e-CALLISTO data and return (data, freqs, time_offsets).

    Ported from fits_io.load_callisto_fits() by Sahan, with improvements:
    - Searches columns by alternative names: frequency/freq, time/times.
    - Detects and corrects transposed axes automatically.
    - Sequential fallback: BIN table → WCS header → FREQMIN/FREQMAX → indices.
    """
    header = hdul[0].header
    raw = hdul[0].data
    if raw is None:
        raise ValueError("HDU[0] contains no image data.")

    data = np.array(raw, dtype=float)
    data = np.squeeze(data)
    while data.ndim > 2:
        data = data[0]
    if data.ndim != 2:
        raise ValueError(f"Expected 2D data after squeeze, got shape={data.shape}.")

    freqs: np.ndarray | None = None
    time: np.ndarray | None = None

    # Look for axes in secondary HDUs (BIN tables)
    for hdu in hdul[1:]:
        try:
            table = hdu.data
        except Exception:
            continue
        if table is None:
            continue
        if freqs is None:
            freqs = _get_col_1d(table, "frequency", "freq")
        if time is None:
            time = _get_col_1d(table, "time", "times")
        if freqs is not None and time is not None:
            break

    # Fallback: WCS from primary header
    if freqs is None:
        freqs = _axis_from_header(header, 2, data.shape[0])
    if freqs is None:
        freqs = _freq_axis_from_range(header, data.shape[0])
    if time is None:
        time = _axis_from_header(header, 1, data.shape[1])

    # Final fallback: integer indices
    if freqs is None:
        logger.warning("Frequency axis not found; using indices")
        freqs = np.arange(data.shape[0], dtype=float)
    if time is None:
        logger.warning("Time axis not found; using indices")
        time = np.arange(data.shape[1], dtype=float)

    freqs = np.asarray(freqs, dtype=float).ravel()
    time = np.asarray(time, dtype=float).ravel()

    # Fix transposition: data must be (n_freq, n_time)
    if data.shape == (len(time), len(freqs)):
        data = data.T
        logger.debug("Transposed axes detected and corrected")
    elif data.shape != (len(freqs), len(time)):
        if len(freqs) != data.shape[0]:
            freqs = np.arange(data.shape[0], dtype=float)
        if len(time) != data.shape[1]:
            time = np.arange(data.shape[1], dtype=float)

    return data, freqs, time


# ── Time axes ────────────────────────────────────────────────────────────────

def _observation_start(header) -> datetime:
    """Resolve observation start time to UTC from DATE-OBS/TIME-OBS."""
    date_obs = str(header.get("DATE-OBS", "1970-01-01")).strip().replace("/", "-")
    time_obs = str(header.get("TIME-OBS", "")).strip()

    # Case 1: DATE-OBS already contains full ISO datetime (DATE-OBS = "YYYY-MM-DDThh:mm:ss")
    if "T" in date_obs:
        try:
            base = datetime.fromisoformat(date_obs.replace("Z", "+00:00"))
            return base if base.tzinfo else base.replace(tzinfo=timezone.utc)
        except Exception:
            pass

    # Case 2: combine DATE-OBS (date only) with TIME-OBS
    date_part = date_obs.split("T")[0]
    time_part = time_obs if time_obs else "00:00:00"
    try:
        return datetime.fromisoformat(f"{date_part}T{time_part}").replace(tzinfo=timezone.utc)
    except Exception:
        return datetime(1970, 1, 1, tzinfo=timezone.utc)


def _times_to_utc(time_arr: np.ndarray, header) -> list[str]:
    """Convert relative time offsets (seconds) to absolute ISO 8601 UTC timestamps.

    Each value in `time_arr` is interpreted as seconds elapsed since the
    observation start (DATE-OBS + TIME-OBS). If CDELT1 is available it is used
    to rescale the axis when the time array consists of integer indices.
    """
    base = _observation_start(header)

    arr = np.asarray(time_arr, dtype=float).ravel()
    # If the array looks like consecutive integer indices (0,1,2,...), rescale with CDELT1
    cdelt1 = header.get("CDELT1")
    if cdelt1 is not None and arr.size > 1:
        diffs = np.diff(arr)
        # Heuristic: if all steps are ~1.0, multiply by CDELT1 (seconds per pixel)
        if np.allclose(diffs, 1.0, atol=1e-3):
            try:
                arr = arr * float(cdelt1)
            except Exception:
                pass

    labels: list[str] = []
    for t in arr:
        ts = base + timedelta(seconds=float(t))
        ms = ts.microsecond // 1000
        labels.append(f"{ts.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z")
    return labels


# ── Scientific processing pipeline (ported from Sahan) ───────────────────────

def _invalid_row_mask(data: np.ndarray) -> np.ndarray:
    """Return True for rows where no value is finite (ported from frequency_axis.py)."""
    return ~np.any(np.isfinite(data), axis=1)


def _subtract_background(data: np.ndarray) -> np.ndarray:
    """Robust per-channel background subtraction.

    Ported from noise_reduction.subtract_background_rows() by Sahan (method 'robust').
    Uses the 25th percentile of each row as the background estimate: robust against
    intense solar emission that raises the higher percentiles.
    """
    arr = np.asarray(data, dtype=np.float32)
    row_invalid = _invalid_row_mask(arr)
    baseline = np.full((arr.shape[0], 1), np.nan, dtype=np.float32)
    valid = ~row_invalid
    if np.any(valid):
        baseline[valid, :] = np.nanpercentile(
            arr[valid, :], 25.0, axis=1, keepdims=True
        ).astype(np.float32)
    out = (arr - baseline).astype(np.float32)
    out[row_invalid, :] = np.nan
    return out


def _detect_persistent_narrowband_rfi(
    data: np.ndarray,
    z_thresh: float = 6.0,
    occupancy_thresh: float = 0.15,
    eps: float = 1e-6,
) -> tuple[np.ndarray, np.ndarray]:
    """Detect persistent narrowband RFI channels by time-occupancy.

    Ported from Burst_No_Burst preprocess/rfi.detect_persistent_narrowband_rfi()
    by Sahan. For each frequency channel, computes a per-channel robust z-score
    over time and flags the channel when the fraction of samples exceeding
    z_thresh is above occupancy_thresh. Far more reliable than level-based
    scoring on background-subtracted data (where channel medians are ~0).

    Returns (2D boolean mask, per-channel occupancy fractions).
    """
    arr = np.asarray(data, dtype=np.float32)
    with warnings.catch_warnings():
        # All-NaN rows (dead channels) are expected; they yield occ=0 below.
        warnings.simplefilter("ignore", category=RuntimeWarning)
        med = np.nanmedian(arr, axis=1, keepdims=True)
        mad = np.nanmedian(np.abs(arr - med), axis=1, keepdims=True)
    with np.errstate(invalid="ignore"):
        z = (arr - med) / (mad + eps)
        occ = np.mean(np.abs(z) > z_thresh, axis=1)
    occ = np.nan_to_num(occ, nan=0.0)
    ch_mask = occ > occupancy_thresh
    mask = np.repeat(ch_mask[:, None], arr.shape[1], axis=1)
    return mask, occ.astype(np.float32)


def _detect_impulsive_rfi(
    data: np.ndarray,
    z_thresh: float = 6.0,
    min_component_size: int = 9,
    eps: float = 1e-6,
) -> np.ndarray:
    """Detect impulsive RFI hotspots via connected components.

    Ported from Burst_No_Burst preprocess/rfi.detect_impulsive_rfi() by Sahan.
    Thresholds the global robust z-score and keeps only connected components
    of at least min_component_size pixels (tiny isolated blips are ignored).
    Component filtering is vectorised with bincount instead of the original
    per-component loop.
    """
    arr = np.asarray(data, dtype=np.float32)
    med = np.nanmedian(arr)
    mad = np.nanmedian(np.abs(arr - med))
    with np.errstate(invalid="ignore"):
        z = (arr - med) / (mad + eps)
        candidate = np.abs(z) > z_thresh
    candidate &= np.isfinite(arr)
    labeled, n_comp = ndi_label(candidate)
    if n_comp == 0:
        return np.zeros_like(candidate, dtype=bool)
    sizes = np.bincount(labeled.ravel())
    keep = np.zeros(n_comp + 1, dtype=bool)
    keep[1:] = sizes[1:] >= max(1, int(min_component_size))
    return keep[labeled]


def _inpaint_with_channel_median(data: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """Replace masked samples with their channel median (global-median fallback).

    Ported from Burst_No_Burst preprocess/rfi.inpaint_with_channel_median() by Sahan.
    """
    arr = np.asarray(data, dtype=np.float32)
    mask = np.asarray(mask, dtype=bool)
    out = arr.copy()

    finite = np.where(np.isfinite(out), out, np.nan)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        row_median = np.nanmedian(finite, axis=1)
        global_median = np.nanmedian(finite)
    if not np.isfinite(global_median):
        global_median = 0.0

    for f in range(out.shape[0]):
        row_mask = mask[f]
        if not row_mask.any():
            continue
        fill = row_median[f]
        if not np.isfinite(fill):
            fill = global_median
        out[f, row_mask] = fill
    return out.astype(np.float32)


def _mitigate_rfi(
    data: np.ndarray,
    *,
    z_thresh: float = 6.0,
    occupancy_thresh: float = 0.15,
    min_component_size: int = 9,
    impulsive: bool = True,
) -> tuple[np.ndarray, list[int], dict]:
    """Full RFI mitigation pipeline (v2). Ported from Burst_No_Burst
    preprocess/rfi.mitigate_rfi() by Sahan.

    Steps:
    1. Persistent narrowband RFI: per-channel occupancy of |z| > z_thresh.
    2. Impulsive RFI: connected components of the global z-score map
       (optional — strong solar bursts can also form large bright components,
       so this stage can be disabled from the UI).
    3. Inpaint every masked sample with its channel median.

    Returns (cleaned_data, masked_channel_indices, stats).
    """
    arr = np.asarray(data, dtype=np.float32)
    if arr.ndim != 2:
        raise ValueError("_mitigate_rfi expects a 2D array (freq, time).")

    persistent_mask, occupancy = _detect_persistent_narrowband_rfi(
        arr, z_thresh=float(z_thresh), occupancy_thresh=float(occupancy_thresh)
    )
    if impulsive:
        impulsive_mask = _detect_impulsive_rfi(
            arr, z_thresh=float(z_thresh), min_component_size=int(min_component_size)
        )
    else:
        impulsive_mask = np.zeros_like(persistent_mask, dtype=bool)
    combined_mask = persistent_mask | impulsive_mask
    cleaned = _inpaint_with_channel_median(arr, combined_mask)

    masked_channels = [int(i) for i in np.where(np.any(persistent_mask, axis=1))[0]]
    stats = {
        "persistent_channels": len(masked_channels),
        "masked_fraction": round(float(combined_mask.mean()), 5),
        "occupancy_mean": round(float(np.mean(occupancy)), 5),
        "impulsive_enabled": bool(impulsive),
    }
    return cleaned.astype(np.float32), masked_channels, stats


def _percentile_clip_global(data: np.ndarray, lo: float = 2.0, hi: float = 98.0) -> tuple[float, float]:
    """Compute vmin (lo percentile) and vmax (hi percentile) over all data.

    The default upper percentile is 98 (instead of 99.5) to increase visual
    contrast: it crushes the most extreme outliers and lets moderate bursts
    stand out clearly against the background.
    """
    vmin = float(np.nanpercentile(data, lo))
    vmax = float(np.nanpercentile(data, hi))
    return vmin, vmax


def _header_to_dict(header) -> dict:
    """Convert a FITS header to a JSON-serializable dict."""
    result: dict = {}
    for key, value in header.items():
        if key in ("COMMENT", "HISTORY", ""):
            continue
        try:
            result[key] = value if isinstance(value, (int, float, str, bool)) else str(value)
        except Exception:
            result[key] = str(value)
    return result


# ── Raw FITS cache (avoids re-parsing the same file on every zoom) ────────────

_RAW_CACHE: OrderedDict[str, tuple] = OrderedDict()
_RAW_CACHE_LOCK = threading.Lock()
_RAW_CACHE_MAX = 8


def _load_raw_cached(
    fits_path: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, object]:
    """Open a FITS file and return (data, freqs, time_arr, header), using an LRU cache.

    The returned arrays are the *raw* unprocessed data — background subtraction
    and RFI cleaning are intentionally NOT applied here so that callers can slice
    first and then process only the relevant region.
    Cached entries are never mutated by callers (all processing functions create
    new arrays), so it is safe to return the arrays without copying.
    """
    with _RAW_CACHE_LOCK:
        if fits_path in _RAW_CACHE:
            _RAW_CACHE.move_to_end(fits_path)
            return _RAW_CACHE[fits_path]
    # Cache miss — load outside the lock so we don't block other threads
    with fits.open(fits_path, memmap=False) as hdul:
        data, freqs, time_arr = _load_callisto_data(hdul)
        header = hdul[0].header.copy()
    entry = (data, freqs, time_arr, header)
    with _RAW_CACHE_LOCK:
        # A concurrent thread may have inserted the same key; prefer its entry
        if fits_path not in _RAW_CACHE:
            _RAW_CACHE[fits_path] = entry
        _RAW_CACHE.move_to_end(fits_path)
        while len(_RAW_CACHE) > _RAW_CACHE_MAX:
            _RAW_CACHE.popitem(last=False)
        return _RAW_CACHE[fits_path]


def _decimate_time(
    data: np.ndarray,
    time_labels: list[str],
    max_cols: int,
) -> tuple[np.ndarray, list[str]]:
    """Block-mean the time axis down to at most max_cols columns.

    Frequencies are NOT decimated. The time labels list is decimated in lockstep
    by taking the first label of each block (the block-start timestamp).
    """
    n_cols = data.shape[1]
    if n_cols <= max_cols:
        return data, time_labels
    k = max(1, n_cols // max_cols)
    n_trim = (n_cols // k) * k
    decimated = data[:, :n_trim].reshape(data.shape[0], n_trim // k, k).mean(axis=2)
    dec_labels = time_labels[::k][: n_trim // k]
    return decimated, dec_labels


def _parse_utc(s: str) -> datetime:
    """Parse an ISO-8601 / Plotly date string to an aware UTC datetime."""
    s = s.strip().replace(" ", "T").rstrip("Z")
    # Strip explicit timezone offset if present (assume UTC)
    s = re.sub(r"[+-]\d{2}:\d{2}$", "", s)
    for fmt in ("%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    raise ValueError(f"Cannot parse timestamp: {s!r}")


# ── Single-station pipeline helper ───────────────────────────────────────────

def _build_spectrogram(
    station: str,
    date: str,
    filename: str | None = None,
    file_path: str | None = None,
    sahan_filter: bool = False,
    max_time_bins: int | None = None,
    rfi_z_thresh: float = 6.0,
    rfi_occupancy: float = 0.15,
    rfi_min_component: int = 9,
    rfi_impulsive: bool = True,
) -> SpectrogramResponse:
    """Resolve a FITS file and run the full processing pipeline for one station.

    Raises FileNotFoundError when no file can be located, RuntimeError on
    processing failures. Never raises HTTPException — callers handle that.

    When max_time_bins is set, the time axis is block-mean decimated BEFORE
    background subtraction, so the processing pipeline operates on the lighter
    decimated matrix. This is the intended path for overview loads.
    """
    if file_path:
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")
        fits_path = file_path
        logger.info("Using explicit file_path: %s", fits_path)
    elif filename:
        local_path = os.path.join(DATA_DIR_LOCAL, filename)
        if os.path.isfile(local_path):
            fits_path = local_path
            logger.info("Using locally cached file: %s", fits_path)
        else:
            fits_path = _download_from_ethz(station, date, filename=filename)
        if not fits_path:
            raise FileNotFoundError(
                f"Could not retrieve '{filename}' for '{station}' on {date}."
            )
    else:
        fits_path = (
            _find_local_fits_file(station, date)
            or _find_nas_fits_file(station, date)
            or _download_from_ethz(station, date)
        )
        if not fits_path:
            raise FileNotFoundError(
                f"No file found for station '{station}' on {date}. "
                "Check the station name or whether the ETHZ server (soleil.i4ds.ch) is reachable."
            )

    logger.info("Processing %s", fits_path)
    try:
        data_raw, freqs, time_arr, header = _load_raw_cached(fits_path)
        time_labels = _times_to_utc(time_arr, header)

        if max_time_bins is not None:
            data, time_labels = _decimate_time(data_raw, time_labels, max_time_bins)
        else:
            data = data_raw

        data = _subtract_background(data)

        rfi_masked: list[int] = []
        rfi_stats: dict = {}
        if sahan_filter:
            data, rfi_masked, rfi_stats = _mitigate_rfi(
                data,
                z_thresh=rfi_z_thresh,
                occupancy_thresh=rfi_occupancy,
                min_component_size=rfi_min_component,
                impulsive=rfi_impulsive,
            )
            logger.info(
                "RFI v2 applied: %d persistent channels, %.2f%% samples masked",
                len(rfi_masked), 100.0 * rfi_stats.get("masked_fraction", 0.0),
            )

        finite_vals = data[np.isfinite(data)]
        if finite_vals.size == 0:
            vmin, vmax = 0.0, 1.0
        else:
            vmin, vmax = _percentile_clip_global(data.astype(float))

        data_out = np.nan_to_num(
            np.array(data, dtype=float),
            nan=0.0,
            posinf=vmax,
            neginf=vmin,
        )

        return SpectrogramResponse(
            station=station,
            date=date,
            filename=os.path.basename(fits_path),
            time_axis=time_labels,
            freq_axis=[round(float(f), 3) for f in freqs],
            z=[[round(float(v), 4) for v in row] for row in data_out.tolist()],
            vmin=round(vmin, 4),
            vmax=round(vmax, 4),
            fits_header=_header_to_dict(header),
            rfi_masked_channels=rfi_masked,
            rfi_stats=rfi_stats,
        )
    except Exception as exc:
        raise RuntimeError(f"Error processing FITS '{fits_path}': {exc}") from exc


_COMBINE_EXECUTOR = ThreadPoolExecutor(max_workers=4, thread_name_prefix="combine")
_MAX_COMBINE_STATIONS = 6


# ── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok", "version": "0.2.0"}


@app.get("/api/stations", response_model=StationsResponse)
def get_stations():
    """Return the live e-Callisto station list by scanning the ETHZ archive.

    Tries the last 7 days to find a day with data. Falls back to the
    static list if ETHZ is unreachable.
    """
    for days_back in range(1, 8):
        dt = datetime.now() - timedelta(days=days_back)
        dir_url = f"{ETHZ_BASE_URL}/{dt.strftime('%Y/%m/%d')}/"
        try:
            req = Request(dir_url, headers={"User-Agent": "AstroDoncel/1.0"})
            with urlopen(req, timeout=10) as resp:
                page = resp.read().decode("utf-8", errors="replace")
            # Extract station name: everything before _YYYYMMDD_HHMMSS_NN.fit[.gz]
            pattern = re.compile(
                r'href="([A-Za-z][A-Za-z0-9_-]*?)_\d{8}_\d{6}_\d{2}\.fit(?:\.gz)?"',
                re.IGNORECASE,
            )
            names = [m.upper() for m in pattern.findall(page)]
            if names:
                unique = sorted(set(names))
                logger.info(
                    "Stations found in ETHZ: %d (date %s)",
                    len(unique),
                    dt.strftime("%Y-%m-%d"),
                )
                return StationsResponse(stations=unique, source="ethz")
        except Exception as exc:
            logger.debug("ETHZ stations failed for %s: %s", dt.strftime("%Y-%m-%d"), exc)
            continue

    logger.warning("ETHZ unreachable for station list; using static fallback")
    return StationsResponse(stations=_STATIONS_FALLBACK, source="static")


@app.get("/api/files", response_model=FilesResponse)
def get_files(
    station: str = Query(..., description="e-Callisto station name"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
):
    """List all burst files available for a station and date.

    Merges locally cached files (already downloaded) with those available on ETHZ.
    Each entry includes the filename and the start time extracted from its name.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    local = set(_list_local_fits_files(station, date))
    ethz = set(_list_ethz_files(station, date))
    all_files = sorted(local | ethz)

    source = "ethz" if ethz else ("local" if local else "none")
    if local and ethz and local != ethz:
        source = "mixed"

    entries: list[FileEntry] = []
    for fn in all_files:
        t = _time_from_filename(fn)
        cached = "★ " if fn in local else ""
        entries.append(FileEntry(filename=fn, time=t, label=f"{cached}{t}"))

    return FilesResponse(station=station, date=date, files=entries, source=source)


@app.get("/api/spectrogram", response_model=SpectrogramResponse)
def get_spectrogram(
    station: str = Query(..., description="e-Callisto station, e.g. SPAIN-SIGUENZA"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    filename: str = Query(default=None, description="Specific FITS filename"),
    file_path: str = Query(default=None, description="Absolute path (manual override)"),
    sahan_filter: bool = Query(default=False, description="Apply full RFI cleaning"),
    max_time_bins: int = Query(default=None, description="Decimate time axis to at most N columns (overview mode)"),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0, description="RFI robust z-score threshold"),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0, description="RFI channel occupancy threshold"),
    rfi_min_component: int = Query(default=9, ge=1, le=500, description="Min connected-component size for impulsive RFI"),
    rfi_impulsive: bool = Query(default=True, description="Enable impulsive (connected-component) RFI stage"),
):
    """Return the spectrogram for an e-Callisto station.

    Resolution order:
    1) explicit file_path
    2) filename → local cache → ETHZ download
    3) first local match → NAS → ETHZ download

    Processing pipeline:
    - Always: robust background subtraction (25th percentile per frequency channel).
    - If sahan_filter=true: additionally applies RFI mitigation v2 (occupancy +
      connected components + channel-median inpainting, from Burst_No_Burst).
    - vmin/vmax are always recomputed on the processed data.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    try:
        return _build_spectrogram(
            station, date,
            filename=filename, file_path=file_path,
            sahan_filter=sahan_filter,
            max_time_bins=max_time_bins,
            rfi_z_thresh=rfi_z_thresh,
            rfi_occupancy=rfi_occupancy,
            rfi_min_component=rfi_min_component,
            rfi_impulsive=rfi_impulsive,
        )
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error processing spectrogram for %s %s", station, date)
        raise HTTPException(status_code=500, detail=f"Error processing FITS: {exc}")


@app.get("/api/spectrogram/combine", response_model=CombinedSpectrogramResponse)
async def get_spectrogram_combine(
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    stations: list[str] = Query(..., description="Station names to combine"),
    filename: str = Query(default=None, description="Primary station filename for 15-min block sync"),
    sahan_filter: bool = Query(default=False, description="Apply full RFI cleaning"),
    max_time_bins: int = Query(default=None, description="Decimate time axis to at most N columns (overview mode)"),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0),
    rfi_min_component: int = Query(default=9, ge=1, le=500),
    rfi_impulsive: bool = Query(default=True),
):
    """Return per-station spectrograms for multiple stations, processed concurrently.

    When `filename` is provided, the primary station (stations[0]) is fetched with
    that exact file and all secondary stations are synced to the same 15-minute block
    by scanning for a file whose HHMM matches the primary's. Stations with no matching
    file for that block are reported in `failed`.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    if not stations:
        raise HTTPException(status_code=422, detail="At least one station is required.")
    if len(stations) > _MAX_COMBINE_STATIONS:
        raise HTTPException(
            status_code=422,
            detail=f"Too many stations requested: {len(stations)} > {_MAX_COMBINE_STATIONS}.",
        )

    # Derive HHMM target for time-sync (strip colons from "HH:MM:SS" → "HHMMSS")
    target_hhmm: str | None = None
    if filename:
        raw = _time_from_filename(filename).replace(":", "")  # "HHMMSS" or "??????"
        if len(raw) >= 4 and raw[:4].isdigit():
            target_hhmm = raw[:4]

    rfi_kwargs = dict(
        rfi_z_thresh=rfi_z_thresh,
        rfi_occupancy=rfi_occupancy,
        rfi_min_component=rfi_min_component,
        rfi_impulsive=rfi_impulsive,
    )

    def _process_one(
        st: str,
        exact_filename: str | None,
        match_hhmm: str | None,
    ) -> tuple[str, SpectrogramResponse | None, str | None]:
        try:
            if exact_filename:
                # Primary station: use the exact file the user selected
                logger.info("combine: station=%s exact_file=%s", st, exact_filename)
                result = _build_spectrogram(
                    st, date, filename=exact_filename,
                    sahan_filter=sahan_filter, max_time_bins=max_time_bins,
                    **rfi_kwargs,
                )
            elif match_hhmm:
                # Secondary station: scan available files and pick the one matching HHMM
                local = set(_list_local_fits_files(st, date))
                ethz = set(_list_ethz_files(st, date))
                all_files = sorted(local | ethz)
                matched = next(
                    (
                        f for f in all_files
                        if _time_from_filename(f).replace(":", "")[:4] == match_hhmm
                    ),
                    None,
                )
                if matched is None:
                    raise FileNotFoundError(
                        f"No file for time block {match_hhmm[:2]}:{match_hhmm[2:]} on {date}."
                    )
                logger.info("combine: station=%s matched_file=%s", st, matched)
                result = _build_spectrogram(
                    st, date, filename=matched,
                    sahan_filter=sahan_filter, max_time_bins=max_time_bins,
                    **rfi_kwargs,
                )
            else:
                # No time anchor was derived — refuse rather than silently loading an
                # arbitrary file, which would produce unsynchronised or duplicated data.
                raise FileNotFoundError(
                    f"No time anchor for station '{st}': cannot determine which "
                    "15-minute block to load. Provide a primary filename."
                )
            return st, result, None
        except Exception as exc:
            logger.warning("combine: %s failed: %s", st, exc)
            return st, None, str(exc)

    # Primary station gets the exact filename; secondaries get HHMM sync
    tasks = [
        (st, filename if (i == 0 and filename) else None, target_hhmm if i > 0 else None)
        for i, st in enumerate(stations)
    ]

    loop = asyncio.get_event_loop()
    futures = [
        loop.run_in_executor(_COMBINE_EXECUTOR, _process_one, st, fname, hhmm)
        for st, fname, hhmm in tasks
    ]
    results = await asyncio.gather(*futures)

    layers: list[SpectrogramResponse] = []
    failed: list[dict] = []
    for st, layer, reason in results:
        if layer is not None:
            layers.append(layer)
        else:
            failed.append({"station": st, "reason": reason})

    if not layers:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for any of the requested stations on {date}.",
        )

    return CombinedSpectrogramResponse(date=date, layers=layers, failed=failed)


# ── High-resolution zoom patch ────────────────────────────────────────────────

# Zoom patches may be denser than the 1500-col overview: this ceiling only
# guards against pathological requests (e.g. full-file zoom at raw resolution).
_MAX_ZOOM_COLS = 2400


@app.get("/api/spectrogram/zoom", response_model=SpectrogramResponse)
def get_spectrogram_zoom(
    station: str = Query(..., description="e-Callisto station"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    filename: str = Query(..., description="Exact filename already shown in the overview"),
    t0: str = Query(..., description="Start time ISO-8601 UTC (from Plotly xaxis.range)"),
    t1: str = Query(..., description="End time ISO-8601 UTC (from Plotly xaxis.range)"),
    f0: float = Query(..., description="Start frequency MHz (from Plotly yaxis.range)"),
    f1: float = Query(..., description="End frequency MHz (from Plotly yaxis.range)"),
    sahan_filter: bool = Query(default=False),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0),
    rfi_min_component: int = Query(default=9, ge=1, le=500),
    rfi_impulsive: bool = Query(default=True),
):
    """Return a maximum-resolution patch for a time+frequency bounding box.

    Uses the raw-data LRU cache so repeated zoom requests on the same file
    do not re-parse the FITS. Background subtraction and optional RFI cleaning
    are recomputed on the slice only, so contrast is optimised for the zoomed
    region — intentional behaviour.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    # Resolve the FITS file (must already be local — overview guarantees this)
    local_path = os.path.join(DATA_DIR_LOCAL, filename)
    if os.path.isfile(local_path):
        fits_path = local_path
    else:
        fits_path = _download_from_ethz(station, date, filename=filename)
    if not fits_path:
        raise HTTPException(
            status_code=404,
            detail=f"File '{filename}' not found for station '{station}' on {date}.",
        )

    try:
        data_raw, freqs, time_arr, header = _load_raw_cached(fits_path)
        time_labels: list[str] = _times_to_utc(time_arr, header)

        # ── Column indices (time) ─────────────────────────────────────────────
        try:
            t0_ts = _parse_utc(t0).timestamp()
            t1_ts = _parse_utc(t1).timestamp()
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=f"Cannot parse time bounds: {exc}")
        if t0_ts > t1_ts:
            t0_ts, t1_ts = t1_ts, t0_ts

        label_ts = np.array([_parse_utc(lb).timestamp() for lb in time_labels])
        col0 = int(np.searchsorted(label_ts, t0_ts, side="left"))
        col1 = int(np.searchsorted(label_ts, t1_ts, side="right"))
        col0 = max(0, col0)
        col1 = min(data_raw.shape[1], col1)

        # ── Row indices (frequency, handle descending axis) ───────────────────
        freqs_arr = np.asarray(freqs)
        f_lo, f_hi = min(f0, f1), max(f0, f1)
        if freqs_arr.size > 1 and freqs_arr[-1] > freqs_arr[0]:
            # Ascending frequency axis
            row0 = int(np.searchsorted(freqs_arr, f_lo, side="left"))
            row1 = int(np.searchsorted(freqs_arr, f_hi, side="right"))
        else:
            # Descending: flip, searchsort, then map back to original indices
            freqs_flip = freqs_arr[::-1]
            r0 = int(np.searchsorted(freqs_flip, f_lo, side="left"))
            r1 = int(np.searchsorted(freqs_flip, f_hi, side="right"))
            n = len(freqs_arr)
            row0 = n - r1
            row1 = n - r0
        row0 = max(0, row0)
        row1 = min(data_raw.shape[0], row1)

        if col1 <= col0 or row1 <= row0:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"Zoom box is outside data range or too narrow "
                    f"(cols {col0}:{col1}, rows {row0}:{row1})."
                ),
            )

        # ── Slice ─────────────────────────────────────────────────────────────
        data_slice = data_raw[row0:row1, col0:col1]
        freqs_slice = freqs_arr[row0:row1]
        time_slice: list[str] = time_labels[col0:col1]

        # Decimate only if the slice is still very wide
        if data_slice.shape[1] > _MAX_ZOOM_COLS:
            data_slice, time_slice = _decimate_time(data_slice, time_slice, _MAX_ZOOM_COLS)

        # ── Process on the slice ──────────────────────────────────────────────
        data_proc = _subtract_background(data_slice)
        rfi_masked: list[int] = []
        rfi_stats: dict = {}
        if sahan_filter:
            data_proc, rfi_masked, rfi_stats = _mitigate_rfi(
                data_proc,
                z_thresh=rfi_z_thresh,
                occupancy_thresh=rfi_occupancy,
                min_component_size=rfi_min_component,
                impulsive=rfi_impulsive,
            )

        finite_vals = data_proc[np.isfinite(data_proc)]
        if finite_vals.size == 0:
            vmin, vmax = 0.0, 1.0
        else:
            vmin, vmax = _percentile_clip_global(data_proc.astype(float))

        data_out = np.nan_to_num(
            np.array(data_proc, dtype=float),
            nan=0.0,
            posinf=vmax,
            neginf=vmin,
        )

        return SpectrogramResponse(
            station=station,
            date=date,
            filename=filename,
            time_axis=time_slice,
            freq_axis=[round(float(f), 3) for f in freqs_slice],
            z=[[round(float(v), 4) for v in row] for row in data_out.tolist()],
            vmin=round(vmin, 4),
            vmax=round(vmax, 4),
            fits_header=_header_to_dict(header),
            rfi_masked_channels=rfi_masked,
            rfi_stats=rfi_stats,
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Zoom failed for %s %s: %s", station, filename, exc)
        raise HTTPException(status_code=500, detail=f"Zoom processing failed: {exc}")


# ── GOES/XRS overlay (ported from goes_overlay.py by Sahan, simplified) ──────

_GOES_CACHE_DIR = os.path.join(DATA_DIR_LOCAL, "goes_cache")
_GOES_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="goes-fido")

# Preferred GOES satellite order by epoch (from goes_overlay.py by Sahan).
def _preferred_goes_satellites(year: int) -> tuple[int, ...]:
    if year >= 2025:
        return (19, 18, 17, 16)
    if year >= 2022:
        return (18, 17, 16, 15, 14, 13)
    if year >= 2017:
        return (17, 16, 15, 14, 13)
    if year >= 2010:
        return (15, 14, 13, 12, 11, 10)
    if year >= 2003:
        return (12, 11, 10, 9, 8)
    if year >= 1997:
        return (10, 9, 8)
    return (9, 8)


def _pick_xrsb_column(columns: list[str]) -> str | None:
    """Select the XRS-B column (long channel, 0.1–0.8 nm) by heuristic scoring.

    Ported from goes_overlay._goes_channel_score() by Sahan.
    """
    best, best_score = None, -10_000
    for col in columns:
        lowered = str(col).strip().lower()
        if not lowered:
            continue
        score = 0
        if lowered == "xrsb_flux":
            score += 160
        if lowered == "b_flux":
            score += 150
        if any(tok in lowered for tok in ("xrsb", "long", "1.0", "8.0")):
            score += 60
        if lowered.startswith("b_"):
            score += 15
        if "flux" in lowered:
            score += 80
        if lowered.endswith("_flux"):
            score += 20
        if any(tok in lowered for tok in ("flag", "quality", "count", "num", "primary", "excluded")):
            score -= 220
        if any(tok in lowered for tok in ("electron", "current")):
            score -= 160
        if score > best_score:
            best, best_score = str(col), score
    return best if best_score > 0 else None


def _fetch_goes_xrsb_sync(date_str: str) -> dict:
    """Download GOES XRS-B data via sunpy.net.Fido for a full UTC day.

    Returns {"times": [...iso8601], "xrsb": [...W/m²], "satellite": int}.
    """
    try:
        from sunpy.net import Fido, attrs as a
        from sunpy import timeseries as ts
    except ImportError as exc:
        raise RuntimeError(
            f"sunpy is not installed in the backend ({exc}). "
            "Install with: pip install 'sunpy[net,timeseries]'"
        )

    target = datetime.strptime(date_str, "%Y-%m-%d")
    start = target.strftime("%Y-%m-%d 00:00:00")
    end = target.strftime("%Y-%m-%d 23:59:59")
    os.makedirs(_GOES_CACHE_DIR, exist_ok=True)

    sats = _preferred_goes_satellites(target.year)
    last_err: Exception | None = None

    for sat in sats:
        try:
            logger.info("Searching GOES-%d XRS for %s in SunPy archive…", sat, date_str)
            try:
                query = Fido.search(
                    a.Time(start, end),
                    a.Instrument.xrs,
                    a.goes.SatelliteNumber(sat),
                )
            except AttributeError:
                # Older alternative API
                query = Fido.search(
                    a.Time(start, end),
                    a.Instrument("XRS"),
                    a.goes.SatelliteNumber(sat),
                )
            if len(query) == 0 or sum(len(t) for t in query) == 0:
                continue

            paths = Fido.fetch(query, path=os.path.join(_GOES_CACHE_DIR, "{file}"))
            if len(paths) == 0:
                continue

            tseries = ts.TimeSeries(list(paths), concatenate=True)
            df = tseries.to_dataframe()
            numeric_cols = [c for c in df.columns if np.issubdtype(df[c].dtype, np.number)]
            if not numeric_cols:
                continue

            col_b = _pick_xrsb_column(numeric_cols) or numeric_cols[-1]
            flux = np.asarray(df[col_b].values, dtype=float)

            idx = df.index
            times_py = idx.to_pydatetime() if hasattr(idx, "to_pydatetime") else list(idx)

            out_times: list[str] = []
            out_flux: list[float] = []
            for t, f in zip(times_py, flux):
                if not np.isfinite(f) or f <= 0.0:
                    continue
                if hasattr(t, "tzinfo") and t.tzinfo is None:
                    t = t.replace(tzinfo=timezone.utc)
                if not (target.date() == t.date() if hasattr(t, "date") else True):
                    continue
                ms = t.microsecond // 1000 if hasattr(t, "microsecond") else 0
                out_times.append(f"{t.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z")
                out_flux.append(float(f))

            if out_times:
                logger.info("GOES-%d XRS: %d valid samples", sat, len(out_times))
                return {"times": out_times, "xrsb": out_flux, "satellite": sat}
        except Exception as exc:
            logger.debug("GOES-%d failed: %s", sat, exc)
            last_err = exc
            continue

    raise RuntimeError(
        f"No GOES/XRS data found for {date_str}"
        + (f" ({last_err})" if last_err else "")
    )


@app.get("/api/goes", response_model=GoesResponse)
async def get_goes(date: str = Query(..., description="Date YYYY-MM-DD")):
    """Return GOES XRS-B flux (0.1–0.8 nm channel) for a full UTC day.

    Source: SunPy/Fido archive (NOAA NGDC / NCEI). Covers from approximately
    1986 onwards across all GOES satellite generations.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(_GOES_EXECUTOR, _fetch_goes_xrsb_sync, date)
    except Exception as exc:
        logger.warning("GOES not available for %s: %s", date, exc)
        return GoesResponse(
            date=date,
            available=False,
            reason=str(exc),
            times=[],
            xrsb=[],
            satellite=None,
        )

    return GoesResponse(
        date=date,
        available=True,
        reason="",
        times=result["times"],
        xrsb=result["xrsb"],
        satellite=result.get("satellite"),
    )


# uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
