"""
AstroDoncel API — FastAPI backend for e-CALLISTO spectrograms.
Scientific engine adapted from e-CALLISTO FITS Analyzer (Sahan S. Liyanage, through v2.8.0).
"""

from __future__ import annotations

import asyncio
import glob
import html
import json
import logging
import os
import re
import threading
import time
import uuid
import warnings
from collections import OrderedDict
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone
from urllib.error import URLError
from urllib.request import Request, urlopen

import numpy as np
from astropy.io import fits
from fastapi import FastAPI, HTTPException, Query
from fastapi import Request as FastAPIRequest
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from scipy.ndimage import label as ndi_label
from sqlalchemy import select

from backend.api_features import router as feature_router
from backend.db import FitsFile, GoesDay, Station, init_db, session_scope
from backend.security import safe_join, validate_date, validate_filename_context, validate_station

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(_app: FastAPI):
    """Prepare mandatory local state before accepting traffic."""
    os.makedirs(DATA_DIR_LOCAL, exist_ok=True)
    os.makedirs(os.environ.get("TASK_RESULT_DIR", os.path.join("data", "task_results")), exist_ok=True)
    init_db()
    yield


app = FastAPI(title="AstroDoncel API", version="0.4.0", lifespan=lifespan)
app.add_middleware(GZipMiddleware, minimum_size=1024, compresslevel=6)
app.include_router(feature_router)


@app.middleware("http")
async def request_observability(request: FastAPIRequest, call_next):
    request_id = request.headers.get("x-request-id", str(uuid.uuid4()))[:64]
    started = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = (time.perf_counter() - started) * 1000.0
    response.headers["X-Request-ID"] = request_id
    response.headers["Server-Timing"] = f"app;dur={elapsed_ms:.1f}"
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
    logger.info("request id=%s method=%s path=%s status=%s duration_ms=%.1f", request_id, request.method, request.url.path, response.status_code, elapsed_ms)
    return response


def _cors_origins() -> list[str]:
    configured = os.environ.get("FRONTEND_ORIGINS", "")
    if configured.strip():
        return [origin.strip().rstrip("/") for origin in configured.split(",") if origin.strip()]
    return ["http://localhost:5173", "http://127.0.0.1:5173"]


app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins(),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR_LOCAL = os.path.normpath(
    os.environ.get(
        "DATA_DIR_LOCAL",
        os.path.join(os.path.dirname(__file__), "..", "data"),
    )
)
ECALLISTO_DATA_DIR = os.environ.get(
    "ECALLISTO_DATA_DIR", "/var/services/web/ecallistodata"
)
ETHZ_BASE_URL = "http://soleil.i4ds.ch/solarradio/data/2002-20yy_Callisto"
_DOWNLOAD_LOCKS: dict[str, threading.Lock] = {}
_DOWNLOAD_LOCKS_GUARD = threading.Lock()

# Static fallback list — 76 real stations extracted from the ETHZ archive
# (generated by scanning multiple dates from 2024-2026)
_STATIONS_FALLBACK: list[str] = [
    "ALASKA-ANCHORAGE",
    "ALASKA-COHOE",
    "ALASKA-HAARP",
    "ALGERIA-CRAAG",
    "ALMATY",
    "AUSTRALIA-ASSA",
    "AUSTRIA-KRUMBACH",
    "AUSTRIA-MICHELBACH",
    "AUSTRIA-OE3FLB",
    "AUSTRIA-UNIGRAZ",
    "BIR",
    "BRAZIL",
    "CROATIA-VISNJAN",
    "DENMARK",
    "EGYPT-ALEXANDRIA",
    "EGYPT-SPACEAGENCY",
    "ETHIOPIA",
    "FINLAND-KEMPELE",
    "FINLAND-RUISSALO",
    "FINLAND-SIUNTIO",
    "GERMANY-DLR",
    "GERMANY-ESSEN",
    "GLASGOW",
    "GREENLAND",
    "HUMAIN",
    "HURBANOVO",
    "INDIA-GAURI",
    "INDIA-OOTY",
    "INDIA-UDAIPUR",
    "INDONESIA",
    "ITALY-STRASSOLT",
    "JAPAN-IBARAKI",
    "KASI",
    "MALAYSIA-BANTING",
    "MEXART",
    "MEXICO-ENSENADA-UNAM",
    "MEXICO-FCFM-UANL",
    "MEXICO-FCFM-UNACH",
    "MEXICO-LANCE",
    "MEXICO-LANCE-A",
    "MEXICO-LANCE-B",
    "MEXICO-UANL-INFIERNILLO",
    "MONGOLIA-UB",
    "MRO",
    "MRT1",
    "NASA-GSFC",
    "NORWAY-EGERSUND",
    "NORWAY-NY-AALESUND",
    "NORWAY-RANDABERG",
    "NZ-WAIRAKEI-DLR",
    "PARAGUAY",
    "POLAND-BALDY",
    "POLAND-GROTNIKI",
    "ROMANIA",
    "ROSWELL-NM",
    "RWANDA",
    "SPAIN-PERALEJOS",
    "SPAIN-SIGUENZA",
    "SRI-LANKA",
    "SSRT",
    "SWISS-BLEN5M-E",
    "SWISS-CALU",
    "SWISS-FM",
    "SWISS-HB9SCT",
    "SWISS-HEITERSWIL",
    "SWISS-IRSOL",
    "SWISS-LANDSCHLACHT",
    "SWISS-MUHEN",
    "TAIWAN-NCU",
    "TRIEST",
    "TURKEY",
    "UNAM",
    "URUGUAY",
    "USA-ARIZONA-ERAU",
    "USA-BOSTON",
    "UZBEKISTAN",
]


# Approximate geographic coordinates (latitude, longitude in degrees) for the
# e-CALLISTO network. Values are best-effort from the public station catalogue
# and are only used to place markers on the world map — precision to the city /
# observatory level is sufficient. Stations reported by ETHZ but absent here are
# still returned by /api/stations; they simply cannot be plotted.
_STATIONS_GEO: dict[str, tuple[float, float]] = {
    "ALASKA-ANCHORAGE": (61.218, -149.900),
    "ALASKA-COHOE": (60.420, -151.260),
    "ALASKA-HAARP": (62.390, -145.150),
    "ALGERIA-CRAAG": (36.800, 3.050),
    "ALMATY": (43.240, 76.910),
    "AUSTRALIA-ASSA": (-34.960, 138.600),
    "AUSTRIA-KRUMBACH": (47.510, 9.900),
    "AUSTRIA-MICHELBACH": (48.050, 15.790),
    "AUSTRIA-OE3FLB": (48.100, 15.800),
    "AUSTRIA-UNIGRAZ": (47.070, 15.440),
    "BIR": (53.090, -7.920),
    "BRAZIL": (-23.200, -45.860),
    "CROATIA-VISNJAN": (45.280, 13.720),
    "DENMARK": (55.680, 12.570),
    "EGYPT-ALEXANDRIA": (31.200, 29.920),
    "EGYPT-SPACEAGENCY": (30.030, 31.210),
    "ETHIOPIA": (9.030, 38.740),
    "FINLAND-KEMPELE": (64.910, 25.500),
    "FINLAND-RUISSALO": (60.430, 22.170),
    "FINLAND-SIUNTIO": (60.140, 24.190),
    "GERMANY-DLR": (50.850, 7.130),
    "GERMANY-ESSEN": (51.460, 7.010),
    "GLASGOW": (55.870, -4.290),
    "GREENLAND": (64.180, -51.720),
    "HUMAIN": (50.190, 5.250),
    "HURBANOVO": (47.870, 18.190),
    "INDIA-GAURI": (18.500, 73.850),
    "INDIA-OOTY": (11.410, 76.690),
    "INDIA-UDAIPUR": (24.580, 73.710),
    "INDONESIA": (-6.900, 107.600),
    "ITALY-STRASSOLT": (45.970, 13.320),
    "JAPAN-IBARAKI": (36.340, 140.450),
    "KASI": (36.400, 127.370),
    "LEARMONTH": (-22.220, 114.100),
    "MALAYSIA-BANTING": (2.820, 101.500),
    "MAURITIUS": (-20.200, 57.500),
    "MEXART": (20.360, -101.330),
    "MEXICO-ENSENADA-UNAM": (31.870, -116.670),
    "MEXICO-FCFM-UANL": (25.720, -100.310),
    "MEXICO-FCFM-UNACH": (16.750, -93.110),
    "MEXICO-LANCE": (19.700, -101.200),
    "MEXICO-LANCE-A": (19.700, -101.200),
    "MEXICO-LANCE-B": (19.700, -101.200),
    "MEXICO-UANL-INFIERNILLO": (25.500, -100.000),
    "MONGOLIA-UB": (47.920, 106.920),
    "MRO": (-26.700, 116.600),
    "MRT1": (-20.200, 57.600),
    "NASA-GSFC": (38.990, -76.840),
    "NORWAY-EGERSUND": (58.450, 5.990),
    "NORWAY-NY-AALESUND": (78.920, 11.930),
    "NORWAY-RANDABERG": (59.000, 5.600),
    "NZ-WAIRAKEI-DLR": (-38.630, 176.100),
    "PARAGUAY": (-25.300, -57.600),
    "PERU-ICA": (-14.080, -75.730),
    "PHOENIX": (47.340, 8.110),
    "POLAND-BALDY": (53.600, 20.600),
    "POLAND-GROTNIKI": (51.800, 19.300),
    "ROMANIA": (44.400, 26.100),
    "ROSWELL-NM": (33.390, -104.520),
    "RWANDA": (-1.950, 30.060),
    "SPAIN-PERALEJOS": (40.650, -1.860),
    "SPAIN-SIGUENZA": (41.070, -2.640),
    "SRI-LANKA": (6.900, 79.860),
    "SSRT": (51.750, 102.220),
    "SWISS-BLEN5M-E": (47.340, 8.110),
    "SWISS-CALU": (47.000, 8.000),
    "SWISS-FM": (47.300, 8.100),
    "SWISS-HB9SCT": (47.300, 8.000),
    "SWISS-HEITERSWIL": (47.350, 9.100),
    "SWISS-IRSOL": (46.000, 8.960),
    "SWISS-LANDSCHLACHT": (47.600, 9.200),
    "SWISS-MUHEN": (47.300, 8.060),
    "TAIWAN-NCU": (24.970, 121.190),
    "TRIEST": (45.650, 13.780),
    "TURKEY": (39.900, 32.800),
    "UNAM": (19.330, -99.180),
    "URUGUAY": (-34.900, -56.200),
    "USA-ARIZONA-ERAU": (34.610, -112.450),
    "USA-BOSTON": (42.360, -71.060),
    "UZBEKISTAN": (41.330, 69.290),
}


# ── Station coordinate registry (authoritative: from FITS headers) ────────────
# Each CALLISTO FITS file declares its own site: OBS_LAT / OBS_LAC (N|S) and
# OBS_LON / OBS_LOC (E|W). That is the real source of truth, so we harvest
# coordinates from the data itself and persist them. `_STATIONS_GEO` above is
# only a fallback used until a station's real coordinates have been learned.
_COORD_REGISTRY_PATH = os.path.join(DATA_DIR_LOCAL, "station_coords.json")
_COORD_REGISTRY: dict[str, dict] = {}
_COORD_REGISTRY_LOCK = threading.Lock()
_COORD_REGISTRY_LOADED = False
_LOCAL_HARVEST_DONE = False
_COORD_ATTEMPTS: dict[str, float] = {}       # station -> last download-harvest ts
_COORD_ATTEMPT_COOLDOWN = 6 * 3600.0         # don't re-download a failing station too often
_COORD_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="coords")


def _load_coord_registry() -> None:
    global _COORD_REGISTRY, _COORD_REGISTRY_LOADED
    with _COORD_REGISTRY_LOCK:
        if _COORD_REGISTRY_LOADED:
            return
        try:
            with open(_COORD_REGISTRY_PATH, "r", encoding="utf-8") as fh:
                loaded = json.load(fh)
            if isinstance(loaded, dict):
                _COORD_REGISTRY = loaded
        except Exception:
            _COORD_REGISTRY = {}
        _COORD_REGISTRY_LOADED = True


def _save_coord_registry() -> None:
    try:
        os.makedirs(DATA_DIR_LOCAL, exist_ok=True)
        with _COORD_REGISTRY_LOCK:
            snapshot = dict(_COORD_REGISTRY)
        tmp = _COORD_REGISTRY_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(snapshot, fh, indent=0, sort_keys=True)
        os.replace(tmp, _COORD_REGISTRY_PATH)
    except Exception as exc:
        logger.debug("Could not persist coord registry: %s", exc)


def _coords_from_header(header) -> tuple[float, float] | None:
    """Extract (lat, lon) in signed degrees from CALLISTO OBS_* header keywords."""
    try:
        lat_raw = header.get("OBS_LAT")
        lon_raw = header.get("OBS_LON")
        if lat_raw is None or lon_raw is None:
            return None
        lat = abs(float(lat_raw))
        lon = abs(float(lon_raw))
        if str(header.get("OBS_LAC", "N")).strip().upper().startswith("S"):
            lat = -lat
        if str(header.get("OBS_LOC", "E")).strip().upper().startswith("W"):
            lon = -lon
        if not (np.isfinite(lat) and np.isfinite(lon)):
            return None
        if abs(lat) < 1e-6 and abs(lon) < 1e-6:
            return None  # (0, 0) means the station left the field unset
        if not (-90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0):
            return None
        return round(lat, 4), round(lon, 4)
    except Exception:
        return None


def _record_station_coords(station: str, header) -> bool:
    """Persist FITS-derived coordinates for a station. Returns True if updated."""
    coords = _coords_from_header(header)
    if not coords:
        return False
    name = station.upper()
    entry = {"lat": coords[0], "lon": coords[1], "source": "fits"}
    _load_coord_registry()
    with _COORD_REGISTRY_LOCK:
        if _COORD_REGISTRY.get(name) == entry:
            return False
        _COORD_REGISTRY[name] = entry
    _save_coord_registry()
    try:
        with session_scope() as session:
            station = session.get(Station, name)
            if station is None:
                session.add(Station(name=name, lat=coords[0], lon=coords[1], coord_source="fits"))
            else:
                station.lat = coords[0]
                station.lon = coords[1]
                station.coord_source = "fits"
                station.updated_at = datetime.now(timezone.utc)
    except Exception as exc:
        logger.debug("Could not persist station coordinates in database: %s", exc)
    logger.info("Learned coordinates for %s from FITS: %.4f, %.4f", name, *coords)
    return True


def _station_from_filename(filename: str) -> str | None:
    """Return the STATION prefix (upper-case) of a CALLISTO filename."""
    m = re.match(r"([A-Za-z0-9][A-Za-z0-9_-]*?)_\d{8}_\d{6}", filename)
    return m.group(1).upper() if m else None


def _harvest_coords_from_local() -> int:
    """Populate the registry from locally cached FITS files (one per station)."""
    global _LOCAL_HARVEST_DONE
    _load_coord_registry()
    with _COORD_REGISTRY_LOCK:
        if _LOCAL_HARVEST_DONE:
            return 0
        _LOCAL_HARVEST_DONE = True
    if not os.path.isdir(DATA_DIR_LOCAL):
        return 0

    by_station: dict[str, str] = {}
    for path in glob.glob(os.path.join(DATA_DIR_LOCAL, "*.fit*")):
        st = _station_from_filename(os.path.basename(path))
        if st:
            by_station.setdefault(st, path)

    added = 0
    for st, path in by_station.items():
        with _COORD_REGISTRY_LOCK:
            cur = _COORD_REGISTRY.get(st)
        if cur and cur.get("source") == "fits":
            continue
        try:
            with fits.open(path, memmap=False) as hdul:
                if _record_station_coords(st, hdul[0].header):
                    added += 1
        except Exception:
            continue
    if added:
        logger.info("Harvested %d station coordinates from local FITS files", added)
    return added


def _harvest_coords_by_download(stations: list[str], date: str) -> None:
    """Background task: fetch one FITS per station and learn its coordinates."""
    for st in stations:
        try:
            path = (
                _find_local_fits_file(st, date)
                or _find_nas_fits_file(st, date)
                or _download_from_ethz(st, date)
            )
            if not path:
                continue
            with fits.open(path, memmap=False) as hdul:
                _record_station_coords(st, hdul[0].header)
        except Exception as exc:
            logger.debug("Coord harvest failed for %s: %s", st, exc)


def _resolve_station_coords(name: str) -> tuple[float, float, str] | None:
    """Return (lat, lon, source) — FITS registry first, hand fallback second."""
    try:
        with session_scope() as session:
            persisted = session.get(Station, name.upper())
            if persisted and persisted.lat is not None and persisted.lon is not None:
                return float(persisted.lat), float(persisted.lon), persisted.coord_source or "fits"
    except Exception as exc:
        logger.debug("Database coordinate lookup unavailable: %s", exc)
    _load_coord_registry()
    with _COORD_REGISTRY_LOCK:
        reg = _COORD_REGISTRY.get(name)
    if reg:
        return float(reg["lat"]), float(reg["lon"]), "fits"
    fb = _STATIONS_GEO.get(name)
    if fb:
        return fb[0], fb[1], "approx"
    return None


# ── Models ───────────────────────────────────────────────────────────────────

class SpectrogramResponse(BaseModel):
    station: str
    date: str
    filename: str
    time_axis: list[str]
    freq_axis: list[float]
    z: list[list[float]]
    vmin: float
    vmax: float
    fits_header: dict
    rfi_masked_channels: list[int] = Field(default_factory=list)
    rfi_stats: dict = Field(default_factory=dict)
    unit: str = "relative digits"
    scale_mode: str = "relative"


class CombinedSpectrogramResponse(BaseModel):
    date: str
    layers: list[SpectrogramResponse]
    failed: list[dict]   # [{station, reason}, ...] for stations with no data


class BurstDetectResponse(BaseModel):
    model_config = {"protected_namespaces": ()}  # allow the model_version field

    station: str
    date: str
    filename: str
    available: bool
    reason: str = ""
    model_version: str | None = None
    threshold: float | None = None
    file_score: float | None = None
    is_burst: bool | None = None
    is_candidate: bool | None = None
    n_windows: int | None = None
    inference_ms: float | None = None
    event_source: str | None = None
    events: list[dict] = Field(default_factory=list)


class GoesResponse(BaseModel):
    date: str
    available: bool
    reason: str
    times: list[str]
    xrsb: list[float]
    satellite: int | None = None


class StationsResponse(BaseModel):
    stations: list[str]
    source: str
    reference_date: str = ""
    refreshed_at: datetime | None = None
    retention_days: int = 90
    details: list[dict] = Field(default_factory=list)


class StationGeo(BaseModel):
    station: str
    lat: float
    lon: float
    operative: bool
    burst_count: int = 0        # bursts recorded by this station in `burst_month`
    coord_source: str = "approx"  # "fits" (from station data) | "approx" (fallback)


class StationsGeoResponse(BaseModel):
    stations: list[StationGeo]
    source: str
    operative_count: int
    total_count: int
    reference_date: str  # last ETHZ day scanned for "operative" status, or ""
    burst_month: str = ""  # "YYYY-MM" of the burst list used, or "" if unavailable
    burst_total: int = 0   # total burst-station detections counted that month
    unmapped: list[str] = Field(default_factory=list)   # live stations we have no coordinates for (yet)
    fits_coord_count: int = 0  # how many plotted coords came from real FITS headers
    retention_days: int = 90


class FileEntry(BaseModel):
    filename: str
    time: str    # "HH:MM:SS"
    label: str   # display label for the UI
    focus_code: str | None = None


class FilesResponse(BaseModel):
    station: str
    date: str
    files: list[FileEntry]
    source: str  # "local", "ethz", "mixed"


# ── I/O helpers ──────────────────────────────────────────────────────────────

def _open_fits(path: str):
    """Open a FITS file (supports .fit, .fits, .fit.gz, .fits.gz)."""
    try:
        return fits.open(path, memmap=False)
    except Exception as exc:
        logger.error("Failed to open %s: %s", path, exc)
        raise HTTPException(status_code=500, detail=f"Could not open FITS file: {exc}")


def _find_local_fits_file(station: str, date: str) -> str | None:
    """Search the local cache by exact station token and observation date."""
    if not os.path.isdir(DATA_DIR_LOCAL):
        return None
    # Match by station + specific date
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
        date_str = dt.strftime("%Y%m%d")
        for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
            matches = glob.glob(os.path.join(DATA_DIR_LOCAL, f"{station.upper()}_{date_str}_*{ext}"))
            if matches:
                return sorted(matches)[0]
    except ValueError:
        pass
    return None


def _find_nas_fits_file(station: str, date: str) -> str | None:
    """Search NAS structure at ECALLISTO_DATA_DIR/YYYY/MM/DD/."""
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return None
    date_dir = os.path.join(
        ECALLISTO_DATA_DIR, dt.strftime("%Y"), dt.strftime("%m"), dt.strftime("%d")
    )
    if not os.path.isdir(date_dir):
        return None
    for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
        matches = glob.glob(os.path.join(date_dir, f"{station.upper()}_*{ext}"))
        if matches:
            return sorted(matches)[0]
    return None


def _time_from_filename(filename: str) -> str:
    """Extract start time as HH:MM:SS from a CALLISTO filename.

    Handles all naming variants: with or without the trailing _NN segment,
    and both .fit / .fits / .fit.gz / .fits.gz extensions.
    """
    m = re.search(r'_\d{8}_(\d{2})(\d{2})(\d{2})', filename)
    if m:
        return f"{m.group(1)}:{m.group(2)}:{m.group(3)}"
    return "??:??:??"


def _focus_code_from_filename(filename: str) -> str | None:
    match = re.search(r"_([A-Za-z0-9-]+)\.fits?(?:\.gz)?$", filename, re.IGNORECASE)
    return match.group(1) if match else None


def _list_local_fits_files(station: str, date: str) -> list[str]:
    """Return locally cached filenames for the given station/date."""
    if not os.path.isdir(DATA_DIR_LOCAL):
        return []
    try:
        dt = datetime.strptime(date, "%Y-%m-%d")
        date_str = dt.strftime("%Y%m%d")
    except ValueError:
        return []
    found: list[str] = []
    for ext in (".fit.gz", ".fits.gz", ".fit", ".fits"):
        for path in glob.glob(
            os.path.join(DATA_DIR_LOCAL, f"{station.upper()}_{date_str}_*{ext}")
        ):
            found.append(os.path.basename(path))
    return sorted(set(found))


_ARCHIVE_DAY_CACHE: dict[str, tuple[float, dict[str, list[str]]]] = {}
_ARCHIVE_DAY_CACHE_LOCK = threading.Lock()


def _archive_inventory_for_date(date: str) -> dict[str, list[str]]:
    """Return the live archive's station-to-filenames inventory for one UTC day."""
    try:
        validate_date(date)
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return {}
    now = datetime.now(timezone.utc).timestamp()
    ttl = float(os.environ.get("ARCHIVE_INDEX_REFRESH_MINUTES", "60")) * 60.0
    with _ARCHIVE_DAY_CACHE_LOCK:
        cached = _ARCHIVE_DAY_CACHE.get(date)
    if cached and now - cached[0] < ttl:
        return cached[1]

    dir_url = f"{ETHZ_BASE_URL}/{dt.strftime('%Y/%m/%d')}/"
    try:
        req = Request(dir_url, headers={"User-Agent": "AstroDoncel/1.0"})
        with urlopen(req, timeout=15) as resp:
            page = resp.read().decode("utf-8", errors="replace")
    except Exception:
        return cached[1] if cached else {}

    expected_date = dt.strftime("%Y%m%d")
    inventory: dict[str, list[str]] = {}
    for raw_name in re.findall(r'href="([^"]+\.fits?(?:\.gz)?)"', page, re.IGNORECASE):
        filename = os.path.basename(html.unescape(raw_name))
        station = _station_from_filename(filename)
        if station is None or f"_{expected_date}_" not in filename.upper():
            continue
        inventory.setdefault(station, []).append(filename)
    inventory = {
        station: sorted(set(filenames))
        for station, filenames in inventory.items()
    }
    with _ARCHIVE_DAY_CACHE_LOCK:
        _ARCHIVE_DAY_CACHE[date] = (now, inventory)
    return inventory


def _list_ethz_files(station: str, date: str) -> list[str]:
    """Return the filenames advertised by the live ETHZ archive index."""
    try:
        station = validate_station(station)
    except ValueError:
        return []
    return _archive_inventory_for_date(date).get(station.upper(), [])


def _download_from_ethz(station: str, date: str, filename: str | None = None) -> str | None:
    """Download a FITS file from the ETHZ archive.

    If `filename` is given, downloads that specific file.
    Otherwise, downloads the first file matching station/date.
    Saves to DATA_DIR_LOCAL for reuse in future calls.
    """
    try:
        station = validate_station(station)
        validate_date(date)
        if filename is not None:
            filename = validate_filename_context(filename, station, date)
        dt = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        return None

    dir_url = f"{ETHZ_BASE_URL}/{dt.strftime('%Y/%m/%d')}/"
    os.makedirs(DATA_DIR_LOCAL, exist_ok=True)

    if filename:
        local_path = safe_join(DATA_DIR_LOCAL, filename)
        with _DOWNLOAD_LOCKS_GUARD:
            download_lock = _DOWNLOAD_LOCKS.setdefault(local_path, threading.Lock())
        with download_lock:
            if os.path.isfile(local_path):
                logger.info("File already cached: %s", local_path)
                return local_path
            file_url = dir_url + filename
            temporary_path = f"{local_path}.{uuid.uuid4().hex}.part"
            max_bytes = int(os.environ.get("MAX_FITS_DOWNLOAD_BYTES", str(128 * 1024 * 1024)))
            logger.info("Downloading %s → %s", file_url, local_path)
            try:
                req = Request(file_url, headers={"User-Agent": "AstroDoncel/1.0"})
                downloaded = 0
                with urlopen(req, timeout=120) as resp:
                    declared = resp.headers.get("Content-Length")
                    if declared and int(declared) > max_bytes:
                        raise ValueError(f"Remote FITS exceeds {max_bytes} bytes")
                    with open(temporary_path, "wb") as fh:
                        while chunk := resp.read(512 * 1024):
                            downloaded += len(chunk)
                            if downloaded > max_bytes:
                                raise ValueError(f"Remote FITS exceeds {max_bytes} bytes")
                            fh.write(chunk)
                with fits.open(temporary_path, memmap=False) as downloaded_fits:
                    downloaded_fits.verify("exception")
                    if not downloaded_fits or downloaded_fits[0].data is None:
                        raise ValueError("Downloaded file has no primary FITS data")
                os.replace(temporary_path, local_path)
                logger.info("Download complete (%d bytes)", downloaded)
                with _FILES_CACHE_LOCK:
                    _FILES_CACHE.pop((station.upper(), date), None)
                return local_path
            except Exception as exc:
                logger.error("Failed to download %s: %s", file_url, exc)
                try:
                    os.remove(temporary_path)
                except OSError:
                    pass
                return None

    # No filename: inspect the directory to find the first matching file
    logger.info("Querying ETHZ archive: %s", dir_url)
    try:
        req = Request(dir_url, headers={"User-Agent": "AstroDoncel/1.0"})
        with urlopen(req, timeout=15) as resp:
            page = resp.read().decode("utf-8", errors="replace")
    except URLError as exc:
        logger.warning("Could not reach ETHZ archive: %s", exc)
        return None

    date_str = dt.strftime("%Y%m%d")
    # Permissive: matches with or without trailing _NN, and .fit/.fits/.fit.gz/.fits.gz
    prefix_re = re.compile(
        r'href="(' + re.escape(station.upper()) + r'_' + date_str + r'_\d{6}.*?\.fits?(?:\.gz)?)"',
        re.IGNORECASE,
    )
    matches = sorted(set(prefix_re.findall(page)))
    if not matches:
        all_files = re.findall(r'href="([^"]+\.fits?(?:\.gz)?)"', page, re.IGNORECASE)
        matches = sorted(c for c in all_files if html.unescape(c).upper().startswith(station.upper() + "_"))
    if not matches:
        logger.warning("No files for '%s' in ETHZ on %s", station, date)
        return None

    return _download_from_ethz(station, date, filename=matches[0])


# ── FITS loading (ported from fits_io.load_callisto_fits by Sahan) ───────────

def _get_col_1d(table, *names: str) -> np.ndarray | None:
    """Find a column by name (case-insensitive) and return it as a 1D float array."""
    if table is None:
        return None
    col_names = (
        getattr(table, "names", None)
        or getattr(getattr(table, "dtype", None), "names", None)
        or []
    )
    lowered = {str(n).lower(): str(n) for n in col_names}
    for name in names:
        key = lowered.get(name.lower())
        if key is None:
            continue
        try:
            col = table[key]
            arr = np.array(col)
            if arr.ndim == 0:
                continue
            if arr.ndim == 1:
                return arr.astype(float)
            return arr[0].ravel().astype(float)  # repeated table → first row
        except Exception:
            continue
    return None


def _axis_from_header(header, axis_num: int, length: int) -> np.ndarray | None:
    """Reconstruct an axis from WCS keywords (CRVALn, CDELTn, CRPIXn)."""
    try:
        crval = header.get(f"CRVAL{axis_num}")
        cdelt = header.get(f"CDELT{axis_num}")
        crpix = header.get(f"CRPIX{axis_num}", 1.0)
        if crval is None or cdelt is None:
            return None
        i = np.arange(int(length), dtype=float) + 1.0  # FITS is 1-based
        return float(crval) + (i - float(crpix)) * float(cdelt)
    except Exception:
        return None


def _freq_axis_from_range(header, length: int) -> np.ndarray | None:
    """Reconstruct the frequency axis from FREQMIN/FREQMAX header keywords."""
    try:
        lo = header.get("FREQMIN")
        hi = header.get("FREQMAX")
        if lo is None or hi is None:
            return None
        lo, hi = float(lo), float(hi)
        if not (np.isfinite(lo) and np.isfinite(hi)):
            return None
        # CALLISTO: highest frequency in first row → linspace(hi→lo)
        return np.linspace(max(lo, hi), min(lo, hi), int(length), dtype=float)
    except Exception:
        return None


def _load_callisto_data(hdul) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load e-CALLISTO data and return (data, freqs, time_offsets).

    Ported from fits_io.load_callisto_fits() by Sahan, with improvements:
    - Searches columns by alternative names: frequency/freq, time/times.
    - Detects and corrects transposed axes automatically.
    - Sequential fallback: BIN table → WCS header → FREQMIN/FREQMAX → indices.
    """
    header = hdul[0].header
    raw = hdul[0].data
    if raw is None:
        raise ValueError("HDU[0] contains no image data.")

    data = np.array(raw, dtype=float)
    data = np.squeeze(data)
    while data.ndim > 2:
        data = data[0]
    if data.ndim != 2:
        raise ValueError(f"Expected 2D data after squeeze, got shape={data.shape}.")

    freqs: np.ndarray | None = None
    time: np.ndarray | None = None

    # Look for axes in secondary HDUs (BIN tables)
    for hdu in hdul[1:]:
        try:
            table = hdu.data
        except Exception:
            continue
        if table is None:
            continue
        if freqs is None:
            freqs = _get_col_1d(table, "frequency", "freq")
        if time is None:
            time = _get_col_1d(table, "time", "times")
        if freqs is not None and time is not None:
            break

    # Fallback: WCS from primary header
    if freqs is None:
        freqs = _axis_from_header(header, 2, data.shape[0])
    if freqs is None:
        freqs = _freq_axis_from_range(header, data.shape[0])
    if time is None:
        time = _axis_from_header(header, 1, data.shape[1])

    # Final fallback: integer indices
    if freqs is None:
        logger.warning("Frequency axis not found; using indices")
        freqs = np.arange(data.shape[0], dtype=float)
    if time is None:
        logger.warning("Time axis not found; using indices")
        time = np.arange(data.shape[1], dtype=float)

    freqs = np.asarray(freqs, dtype=float).ravel()
    time = np.asarray(time, dtype=float).ravel()

    # Fix transposition: data must be (n_freq, n_time)
    if data.shape == (len(time), len(freqs)):
        data = data.T
        logger.debug("Transposed axes detected and corrected")
    elif data.shape != (len(freqs), len(time)):
        if len(freqs) != data.shape[0]:
            freqs = np.arange(data.shape[0], dtype=float)
        if len(time) != data.shape[1]:
            time = np.arange(data.shape[1], dtype=float)

    return data, freqs, time


# ── Time axes ────────────────────────────────────────────────────────────────

def _observation_start(header) -> datetime:
    """Resolve observation start time to UTC from DATE-OBS/TIME-OBS."""
    date_obs = str(header.get("DATE-OBS", "1970-01-01")).strip().replace("/", "-")
    time_obs = str(header.get("TIME-OBS", "")).strip()

    # Case 1: DATE-OBS already contains full ISO datetime (DATE-OBS = "YYYY-MM-DDThh:mm:ss")
    if "T" in date_obs:
        try:
            base = datetime.fromisoformat(date_obs.replace("Z", "+00:00"))
            return base if base.tzinfo else base.replace(tzinfo=timezone.utc)
        except Exception:
            pass

    # Case 2: combine DATE-OBS (date only) with TIME-OBS
    date_part = date_obs.split("T")[0]
    time_part = time_obs if time_obs else "00:00:00"
    try:
        return datetime.fromisoformat(f"{date_part}T{time_part}").replace(tzinfo=timezone.utc)
    except Exception:
        return datetime(1970, 1, 1, tzinfo=timezone.utc)


def _time_offsets_seconds(time_arr: np.ndarray, header) -> np.ndarray:
    """Normalise the raw time axis to seconds since observation start.

    If CDELT1 is available it is used to rescale the axis when the time array
    consists of integer indices (steps of ~1.0).
    """
    arr = np.asarray(time_arr, dtype=float).ravel()
    cdelt1 = header.get("CDELT1")
    if cdelt1 is not None and arr.size > 1:
        diffs = np.diff(arr)
        # Heuristic: if all steps are ~1.0, multiply by CDELT1 (seconds per pixel)
        if np.allclose(diffs, 1.0, atol=1e-3):
            try:
                arr = arr * float(cdelt1)
            except Exception:
                pass
    return arr


def _times_to_utc(time_arr: np.ndarray, header) -> list[str]:
    """Convert relative time offsets (seconds) to absolute ISO 8601 UTC timestamps.

    Each value in `time_arr` is interpreted as seconds elapsed since the
    observation start (DATE-OBS + TIME-OBS).
    """
    base = _observation_start(header)
    arr = _time_offsets_seconds(time_arr, header)

    labels: list[str] = []
    for t in arr:
        ts = base + timedelta(seconds=float(t))
        ms = ts.microsecond // 1000
        labels.append(f"{ts.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z")
    return labels


# ── Scientific processing pipeline (ported from Sahan) ───────────────────────

def _invalid_row_mask(data: np.ndarray) -> np.ndarray:
    """Return True for rows where no value is finite (ported from frequency_axis.py)."""
    return ~np.any(np.isfinite(data), axis=1)


def _subtract_background(data: np.ndarray) -> np.ndarray:
    """Robust per-channel background subtraction.

    Ported from noise_reduction.subtract_background_rows() by Sahan (method 'robust').
    Uses the 25th percentile of each row as the background estimate: robust against
    intense solar emission that raises the higher percentiles.
    """
    arr = np.asarray(data, dtype=np.float32)
    row_invalid = _invalid_row_mask(arr)
    baseline = np.full((arr.shape[0], 1), np.nan, dtype=np.float32)
    valid = ~row_invalid
    if np.any(valid):
        baseline[valid, :] = np.nanpercentile(
            arr[valid, :], 25.0, axis=1, keepdims=True
        ).astype(np.float32)
    out = (arr - baseline).astype(np.float32)
    out[row_invalid, :] = np.nan
    return out


def _detect_persistent_narrowband_rfi(
    data: np.ndarray,
    z_thresh: float = 6.0,
    occupancy_thresh: float = 0.15,
    eps: float = 1e-6,
) -> tuple[np.ndarray, np.ndarray]:
    """Detect persistent narrowband RFI channels by time-occupancy.

    Ported from Burst_No_Burst preprocess/rfi.detect_persistent_narrowband_rfi()
    by Sahan. For each frequency channel, computes a per-channel robust z-score
    over time and flags the channel when the fraction of samples exceeding
    z_thresh is above occupancy_thresh. Far more reliable than level-based
    scoring on background-subtracted data (where channel medians are ~0).

    Returns (2D boolean mask, per-channel occupancy fractions).
    """
    arr = np.asarray(data, dtype=np.float32)
    with warnings.catch_warnings():
        # All-NaN rows (dead channels) are expected; they yield occ=0 below.
        warnings.simplefilter("ignore", category=RuntimeWarning)
        med = np.nanmedian(arr, axis=1, keepdims=True)
        mad = np.nanmedian(np.abs(arr - med), axis=1, keepdims=True)
    with np.errstate(invalid="ignore"):
        z = (arr - med) / (mad + eps)
        occ = np.mean(np.abs(z) > z_thresh, axis=1)
    occ = np.nan_to_num(occ, nan=0.0)
    ch_mask = occ > occupancy_thresh
    mask = np.repeat(ch_mask[:, None], arr.shape[1], axis=1)
    return mask, occ.astype(np.float32)


def _detect_impulsive_rfi(
    data: np.ndarray,
    z_thresh: float = 6.0,
    min_component_size: int = 9,
    eps: float = 1e-6,
) -> np.ndarray:
    """Detect impulsive RFI hotspots via connected components.

    Ported from Burst_No_Burst preprocess/rfi.detect_impulsive_rfi() by Sahan.
    Thresholds the global robust z-score and keeps only connected components
    of at least min_component_size pixels (tiny isolated blips are ignored).
    Component filtering is vectorised with bincount instead of the original
    per-component loop.
    """
    arr = np.asarray(data, dtype=np.float32)
    med = np.nanmedian(arr)
    mad = np.nanmedian(np.abs(arr - med))
    with np.errstate(invalid="ignore"):
        z = (arr - med) / (mad + eps)
        candidate = np.abs(z) > z_thresh
    candidate &= np.isfinite(arr)
    labeled, n_comp = ndi_label(candidate)
    if n_comp == 0:
        return np.zeros_like(candidate, dtype=bool)
    sizes = np.bincount(labeled.ravel())
    keep = np.zeros(n_comp + 1, dtype=bool)
    keep[1:] = sizes[1:] >= max(1, int(min_component_size))
    return keep[labeled]


def _inpaint_with_channel_median(data: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """Replace masked samples with their channel median (global-median fallback).

    Ported from Burst_No_Burst preprocess/rfi.inpaint_with_channel_median() by Sahan.
    """
    arr = np.asarray(data, dtype=np.float32)
    mask = np.asarray(mask, dtype=bool)
    out = arr.copy()

    finite = np.where(np.isfinite(out), out, np.nan)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        row_median = np.nanmedian(finite, axis=1)
        global_median = np.nanmedian(finite)
    if not np.isfinite(global_median):
        global_median = 0.0

    for f in range(out.shape[0]):
        row_mask = mask[f]
        if not row_mask.any():
            continue
        fill = row_median[f]
        if not np.isfinite(fill):
            fill = global_median
        out[f, row_mask] = fill
    return out.astype(np.float32)


def _mitigate_rfi(
    data: np.ndarray,
    *,
    z_thresh: float = 6.0,
    occupancy_thresh: float = 0.15,
    min_component_size: int = 9,
    impulsive: bool = True,
) -> tuple[np.ndarray, list[int], dict]:
    """Full RFI mitigation pipeline (v2). Ported from Burst_No_Burst
    preprocess/rfi.mitigate_rfi() by Sahan.

    Steps:
    1. Persistent narrowband RFI: per-channel occupancy of |z| > z_thresh.
    2. Impulsive RFI: connected components of the global z-score map
       (optional — strong solar bursts can also form large bright components,
       so this stage can be disabled from the UI).
    3. Inpaint every masked sample with its channel median.

    Returns (cleaned_data, masked_channel_indices, stats).
    """
    arr = np.asarray(data, dtype=np.float32)
    if arr.ndim != 2:
        raise ValueError("_mitigate_rfi expects a 2D array (freq, time).")

    persistent_mask, occupancy = _detect_persistent_narrowband_rfi(
        arr, z_thresh=float(z_thresh), occupancy_thresh=float(occupancy_thresh)
    )
    if impulsive:
        impulsive_mask = _detect_impulsive_rfi(
            arr, z_thresh=float(z_thresh), min_component_size=int(min_component_size)
        )
    else:
        impulsive_mask = np.zeros_like(persistent_mask, dtype=bool)
    combined_mask = persistent_mask | impulsive_mask
    cleaned = _inpaint_with_channel_median(arr, combined_mask)

    masked_channels = [int(i) for i in np.where(np.any(persistent_mask, axis=1))[0]]
    stats = {
        "persistent_channels": len(masked_channels),
        "masked_fraction": round(float(combined_mask.mean()), 5),
        "occupancy_mean": round(float(np.mean(occupancy)), 5),
        "impulsive_enabled": bool(impulsive),
    }
    return cleaned.astype(np.float32), masked_channels, stats


def _percentile_clip_global(data: np.ndarray, lo: float = 2.0, hi: float = 98.0) -> tuple[float, float]:
    """Compute vmin (lo percentile) and vmax (hi percentile) over all data.

    The default upper percentile is 98 (instead of 99.5) to increase visual
    contrast: it crushes the most extreme outliers and lets moderate bursts
    stand out clearly against the background.
    """
    if not 0 <= lo < hi <= 100:
        raise ValueError("percentile bounds must satisfy 0 <= lo < hi <= 100")
    # Request both bounds together so NumPy performs one order-statistics pass.
    # This follows the v2.8.0 playback/row-statistics optimisation from Sahan's
    # analyzer while keeping AstroDoncel's established 2–98 % display contract.
    vmin, vmax = np.nanpercentile(np.asarray(data), [lo, hi])
    return float(vmin), float(vmax)


def _header_to_dict(header) -> dict:
    """Convert a FITS header to a JSON-serializable dict."""
    result: dict = {}
    for key, value in header.items():
        if key in ("COMMENT", "HISTORY", ""):
            continue
        try:
            result[key] = value if isinstance(value, (int, float, str, bool)) else str(value)
        except Exception:
            result[key] = str(value)
    return result


def _as_aware_utc(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    return value.replace(tzinfo=timezone.utc) if value.tzinfo is None else value.astimezone(timezone.utc)


def _record_fits_metadata(station: str, path: str, header) -> None:
    """Persist searchable FITS metadata without making processing depend on the DB."""
    filename = os.path.basename(path)
    match = re.search(r"_(\d{8})_(\d{6})", filename)
    if not match:
        return
    observed = datetime.strptime("".join(match.groups()), "%Y%m%d%H%M%S").replace(tzinfo=timezone.utc)
    try:
        with session_scope() as session:
            station_name = station.upper()
            row = session.scalar(select(FitsFile).where(FitsFile.filename == filename))
            if row is None:
                row = FitsFile(filename=filename, station=station_name, observed_at=observed)
                session.add(row)
            row.path = path
            row.origin = "nas" if os.path.realpath(path).startswith(os.path.realpath(ECALLISTO_DATA_DIR)) else "cache"
            row.focus_code = _focus_code_from_filename(filename)
            row.fits_header = _header_to_dict(header)
            station_row = session.get(Station, station_name)
            if station_row is None:
                session.add(Station(
                    name=station_name,
                    first_seen_at=observed,
                    last_seen_at=observed,
                ))
            else:
                first_seen = _as_aware_utc(station_row.first_seen_at)
                last_seen = _as_aware_utc(station_row.last_seen_at)
                station_row.first_seen_at = min(first_seen or observed, observed)
                station_row.last_seen_at = max(last_seen or observed, observed)
                station_row.updated_at = datetime.now(timezone.utc)
    except Exception as exc:
        logger.debug("Could not persist FITS metadata: %s", exc)


# ── Raw FITS cache (avoids re-parsing the same file on every zoom) ────────────

_RAW_CACHE: OrderedDict[str, tuple] = OrderedDict()
_RAW_CACHE_LOCK = threading.Lock()
_RAW_CACHE_MAX = 8


def _load_raw_cached(
    fits_path: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, object]:
    """Open a FITS file and return (data, freqs, time_arr, header), using an LRU cache.

    The returned arrays are the *raw* unprocessed data — background subtraction
    and RFI cleaning are intentionally NOT applied here so that callers can slice
    first and then process only the relevant region.
    Cached entries are never mutated by callers (all processing functions create
    new arrays), so it is safe to return the arrays without copying.
    """
    with _RAW_CACHE_LOCK:
        if fits_path in _RAW_CACHE:
            _RAW_CACHE.move_to_end(fits_path)
            return _RAW_CACHE[fits_path]
    # Cache miss — load outside the lock so we don't block other threads
    with fits.open(fits_path, memmap=False) as hdul:
        data, freqs, time_arr = _load_callisto_data(hdul)
        header = hdul[0].header.copy()
    entry = (data, freqs, time_arr, header)
    with _RAW_CACHE_LOCK:
        # A concurrent thread may have inserted the same key; prefer its entry
        if fits_path not in _RAW_CACHE:
            _RAW_CACHE[fits_path] = entry
        _RAW_CACHE.move_to_end(fits_path)
        while len(_RAW_CACHE) > _RAW_CACHE_MAX:
            _RAW_CACHE.popitem(last=False)
        return _RAW_CACHE[fits_path]


def _decimate_time(
    data: np.ndarray,
    time_labels: list[str],
    max_cols: int,
) -> tuple[np.ndarray, list[str]]:
    """Block-mean the time axis down to at most max_cols columns.

    Frequencies are NOT decimated. The time labels list is decimated in lockstep
    by taking the first label of each block (the block-start timestamp).
    """
    n_cols = data.shape[1]
    if n_cols <= max_cols:
        return data, time_labels
    k = max(1, n_cols // max_cols)
    n_trim = (n_cols // k) * k
    decimated = data[:, :n_trim].reshape(data.shape[0], n_trim // k, k).mean(axis=2)
    dec_labels = time_labels[::k][: n_trim // k]
    return decimated, dec_labels


def _parse_utc(s: str) -> datetime:
    """Parse an ISO-8601 / Plotly date string to an aware UTC datetime."""
    s = s.strip().replace(" ", "T").rstrip("Z")
    # Strip explicit timezone offset if present (assume UTC)
    s = re.sub(r"[+-]\d{2}:\d{2}$", "", s)
    for fmt in ("%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    raise ValueError(f"Cannot parse timestamp: {s!r}")


# ── Single-station pipeline helper ───────────────────────────────────────────

def _build_spectrogram(
    station: str,
    date: str,
    filename: str | None = None,
    sahan_filter: bool = False,
    max_time_bins: int | None = None,
    rfi_z_thresh: float = 6.0,
    rfi_occupancy: float = 0.15,
    rfi_min_component: int = 9,
    rfi_impulsive: bool = True,
    scale_mode: str = "relative",
) -> SpectrogramResponse:
    """Resolve a FITS file and run the full processing pipeline for one station.

    Raises FileNotFoundError when no file can be located, RuntimeError on
    processing failures. Never raises HTTPException — callers handle that.

    When max_time_bins is set, the time axis is block-mean decimated BEFORE
    background subtraction, so the processing pipeline operates on the lighter
    decimated matrix. This is the intended path for overview loads.
    """
    station = validate_station(station)
    validate_date(date)
    if filename:
        filename = validate_filename_context(filename, station, date)
        local_path = safe_join(DATA_DIR_LOCAL, filename)
        if os.path.isfile(local_path):
            fits_path = local_path
            logger.info("Using locally cached file: %s", fits_path)
        else:
            fits_path = _download_from_ethz(station, date, filename=filename)
        if not fits_path:
            raise FileNotFoundError(
                f"Could not retrieve '{filename}' for '{station}' on {date}."
            )
    else:
        fits_path = (
            _find_local_fits_file(station, date)
            or _find_nas_fits_file(station, date)
            or _download_from_ethz(station, date)
        )
        if not fits_path:
            raise FileNotFoundError(
                f"No file found for station '{station}' on {date}. "
                "Check the station name or whether the ETHZ server (soleil.i4ds.ch) is reachable."
            )

    logger.info("Processing %s", fits_path)
    try:
        data_raw, freqs, time_arr, header = _load_raw_cached(fits_path)
        if scale_mode not in {"relative", "median_db"}:
            raise ValueError("scale_mode must be relative or median_db")
        if scale_mode == "median_db":
            data_raw = data_raw * (2500.0 / 255.0 / 25.4)
        _record_station_coords(station, header)  # learn the real site from its data
        _record_fits_metadata(station, fits_path, header)
        time_labels = _times_to_utc(time_arr, header)

        if max_time_bins is not None:
            data, time_labels = _decimate_time(data_raw, time_labels, max_time_bins)
        else:
            data = data_raw

        data = _subtract_background(data)

        rfi_masked: list[int] = []
        rfi_stats: dict = {}
        if sahan_filter:
            data, rfi_masked, rfi_stats = _mitigate_rfi(
                data,
                z_thresh=rfi_z_thresh,
                occupancy_thresh=rfi_occupancy,
                min_component_size=rfi_min_component,
                impulsive=rfi_impulsive,
            )
            logger.info(
                "RFI v2 applied: %d persistent channels, %.2f%% samples masked",
                len(rfi_masked), 100.0 * rfi_stats.get("masked_fraction", 0.0),
            )

        finite_vals = data[np.isfinite(data)]
        if finite_vals.size == 0:
            vmin, vmax = 0.0, 1.0
        else:
            vmin, vmax = _percentile_clip_global(data.astype(float))

        data_out = np.nan_to_num(
            np.array(data, dtype=float),
            nan=0.0,
            posinf=vmax,
            neginf=vmin,
        )

        return SpectrogramResponse(
            station=station,
            date=date,
            filename=os.path.basename(fits_path),
            time_axis=time_labels,
            freq_axis=np.round(np.asarray(freqs, dtype=float), 3).tolist(),
            z=np.round(data_out, 4).tolist(),
            vmin=round(vmin, 4),
            vmax=round(vmax, 4),
            fits_header=_header_to_dict(header),
            rfi_masked_channels=rfi_masked,
            rfi_stats=rfi_stats,
            unit="dB" if scale_mode == "median_db" else "relative digits",
            scale_mode=scale_mode,
        )
    except Exception as exc:
        raise RuntimeError(f"Error processing FITS '{fits_path}': {exc}") from exc


_COMBINE_EXECUTOR = ThreadPoolExecutor(max_workers=4, thread_name_prefix="combine")
_MAX_COMBINE_STATIONS = 6


# ── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok", "version": "0.3.0"}


@app.get("/ready")
def readiness():
    from sqlalchemy import text

    database = "ok"
    try:
        with session_scope() as session:
            session.execute(text("SELECT 1"))
    except Exception:
        database = "degraded"
    from backend import burst_detect

    model_ok, model_reason = burst_detect.is_available()
    payload = {
        "status": "ok" if database == "ok" else "degraded",
        "database": database,
        "burst_model": "ok" if model_ok else "unavailable",
        "burst_model_reason": model_reason,
    }
    if database != "ok":
        from fastapi.responses import JSONResponse

        return JSONResponse(status_code=503, content=payload)
    return payload


# e-CALLISTO monthly burst lists (deARCE (v3), UAH / ETHZ). One text file per month
# lists every detected solar radio burst and the stations that recorded it.
_BURSTLIST_BASE = "http://soleil.i4ds.ch/solarradio/data/BurstLists/2010-yyyy_Monstein"
_BURST_CACHE: dict[str, tuple[float, dict[str, int]]] = {}
_BURST_CACHE_TTL = 1800.0  # seconds (monthly file changes at most a few times/day)
_BURST_CACHE_LOCK = threading.Lock()


def _burst_counts_for_month(year: int, month: int) -> dict[str, int]:
    """Return {STATION_UPPER: burst_count} from the monthly e-CALLISTO burst list.

    Counts, per station, the number of burst events it participated in during the
    given month. Results are cached for `_BURST_CACHE_TTL` seconds. Returns an
    empty dict when the list cannot be fetched or parsed.
    """
    key = f"{year:04d}-{month:02d}"
    now = datetime.now(timezone.utc).timestamp()
    with _BURST_CACHE_LOCK:
        cached = _BURST_CACHE.get(key)
        if cached and (now - cached[0]) < _BURST_CACHE_TTL:
            return cached[1]

    url = f"{_BURSTLIST_BASE}/{year:04d}/e-CALLISTO_{year:04d}_{month:02d}.txt"
    counts: dict[str, int] = {}
    try:
        req = Request(url, headers={"User-Agent": "AstroDoncel/1.0"})
        with urlopen(req, timeout=15) as resp:
            text = resp.read().decode("utf-8", errors="replace")
    except Exception as exc:
        logger.debug("Burst list %s unavailable: %s", key, exc)
        with _BURST_CACHE_LOCK:
            _BURST_CACHE[key] = (now, {})
        return {}

    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("Product"):
            continue
        # Columns are tab-separated: Date <tab> Time <tab> Type <tab> Stations
        parts = re.split(r"\t+", line)
        if len(parts) < 4:
            parts = re.split(r"\s{2,}", line)  # fallback if tabs were lost
        if len(parts) < 4:
            continue
        time_field = parts[1]
        if "#" in time_field:  # "##:##-##:##" marks a day with no bursts
            continue
        stations_field = parts[-1]
        for token in stations_field.split(","):
            name = token.strip().upper()
            # Drop any trailing quality annotation like "(good)" if present
            name = re.sub(r"\s*\(.*?\)\s*$", "", name)
            if name:
                counts[name] = counts.get(name, 0) + 1

    with _BURST_CACHE_LOCK:
        _BURST_CACHE[key] = (now, counts)
    logger.info("Burst list %s parsed: %d stations, %d detections",
                key, len(counts), sum(counts.values()))
    return counts


# Cache for the "which stations reported recently" scan. Operative status has
# daily granularity, so a few minutes of caching is accurate — and it means any
# number of client refreshes are served from memory instead of hammering the
# external ETHZ server (soleil.i4ds.ch).
_STATION_SCAN_CACHE: tuple[float, list[str], str] | None = None
_STATION_SCAN_LOCK = threading.Lock()


def _persist_station_inventory(names: list[str], reference_date: str) -> None:
    """Persist archive-derived sightings without overwriting FITS coordinates."""
    if not names or not reference_date:
        return
    observed = datetime.strptime(reference_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    now = datetime.now(timezone.utc)
    with session_scope() as session:
        for name in names:
            station = session.get(Station, name)
            if station is None:
                session.add(Station(
                    name=name,
                    first_seen_at=observed,
                    last_seen_at=observed,
                    updated_at=now,
                ))
            else:
                first_seen = station.first_seen_at
                last_seen = station.last_seen_at
                if first_seen and first_seen.tzinfo is None:
                    first_seen = first_seen.replace(tzinfo=timezone.utc)
                if last_seen and last_seen.tzinfo is None:
                    last_seen = last_seen.replace(tzinfo=timezone.utc)
                station.first_seen_at = min(first_seen or observed, observed)
                station.last_seen_at = max(last_seen or observed, observed)
                station.updated_at = now


def _station_retention_days() -> int:
    try:
        return max(1, min(3650, int(os.environ.get("STATION_RETENTION_DAYS", "90"))))
    except ValueError:
        logger.warning("Invalid STATION_RETENTION_DAYS; using 90")
        return 90


def _known_station_names(reference_date: str = "") -> set[str]:
    """Return stations seen recently, plus FITS-only stations without a sighting date.

    Historical rows remain in the database for provenance, but stations absent
    beyond the configured retention window automatically leave the live UI.
    """
    retention_days = _station_retention_days()
    try:
        anchor = (
            datetime.strptime(reference_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
            if reference_date
            else datetime.now(timezone.utc)
        )
    except ValueError:
        anchor = datetime.now(timezone.utc)
    cutoff = anchor - timedelta(days=retention_days)
    try:
        with session_scope() as session:
            return set(session.scalars(
                select(Station.name).where(
                    Station.last_seen_at.is_(None) | (Station.last_seen_at >= cutoff)
                )
            ).all())
    except Exception as exc:
        logger.debug("Persisted station catalogue unavailable: %s", exc)
        return set()


def _scan_recent_ethz_stations() -> tuple[list[str], str]:
    """Scan the ETHZ archive for the most recent day that has data.

    Returns (sorted unique station names, reference_date 'YYYY-MM-DD'). Results
    are cached for `_STATION_SCAN_TTL` seconds. When ETHZ is unreachable, the
    last good scan is served if available, otherwise ([], "").
    """
    global _STATION_SCAN_CACHE
    now = datetime.now(timezone.utc).timestamp()
    ttl = float(os.environ.get("STATION_REFRESH_MINUTES", "60")) * 60.0
    with _STATION_SCAN_LOCK:
        cached = _STATION_SCAN_CACHE
    if cached and (now - cached[0]) < ttl:
        return cached[1], cached[2]

    latest: tuple[list[str], str] | None = None
    for days_back in range(0, 8):
        dt = datetime.now(timezone.utc) - timedelta(days=days_back)
        ref = dt.strftime("%Y-%m-%d")
        unique = sorted(_archive_inventory_for_date(ref))
        if unique:
            _persist_station_inventory(unique, ref)
            if latest is None:
                latest = (unique, ref)
    if latest is not None:
        unique, ref = latest
        logger.info(
            "Stations found in ETHZ: %d active on %s; recent history persisted",
            len(unique),
            ref,
        )
        with _STATION_SCAN_LOCK:
            _STATION_SCAN_CACHE = (now, unique, ref)
        return unique, ref

    # ETHZ unreachable right now — fall back to the last good scan if we have one.
    if cached:
        logger.warning("ETHZ unreachable; serving cached station scan from %s", cached[2])
        return cached[1], cached[2]
    return [], ""


@app.get("/api/stations", response_model=StationsResponse)
def get_stations():
    """Return all known stations plus archive-derived active/inactive state."""
    reporting, ref_date = _scan_recent_ethz_stations()
    reporting_set = set(reporting)
    known = _known_station_names(ref_date)
    catalog = sorted(known | reporting_set)
    source = "ethz+persisted"
    if not catalog:
        logger.warning("No dynamic station inventory available; using bootstrap fallback")
        catalog = list(_STATIONS_FALLBACK)
        source = "bootstrap"

    persisted: dict[str, Station] = {}
    try:
        with session_scope() as session:
            persisted = {
                item.name: item
                for item in session.scalars(select(Station).where(Station.name.in_(catalog))).all()
            }
    except Exception as exc:
        logger.debug("Station activity details unavailable: %s", exc)
    details = []
    for name in catalog:
        stored = persisted.get(name)
        details.append({
            "station": name,
            "active": name in reporting_set,
            "first_seen_at": stored.first_seen_at.isoformat() if stored and stored.first_seen_at else None,
            "last_seen_at": stored.last_seen_at.isoformat() if stored and stored.last_seen_at else None,
            "coordinate_source": stored.coord_source if stored else None,
        })
    return StationsResponse(
        stations=catalog,
        source=source,
        reference_date=ref_date,
        refreshed_at=datetime.now(timezone.utc),
        retention_days=_station_retention_days(),
        details=details,
    )


@app.get("/api/stations/geo", response_model=StationsGeoResponse)
def get_stations_geo():
    """Return mappable stations with coordinates and live operative status.

    A station is flagged *operative* when it reported at least one file on the
    most recent day scanned in the ETHZ archive. When ETHZ is unreachable the
    catalogue is still returned, but every station is marked non-operative and
    `reference_date` is empty so the frontend can indicate the status is stale.
    """
    reporting, ref_date = _scan_recent_ethz_stations()
    reporting_set = set(reporting)

    # Fill the coordinate registry from any FITS files we already have on disk.
    _harvest_coords_from_local()

    # Burst counts come from the current month's list (fall back to the ETHZ
    # reference month if "now" has no list yet).
    anchor = datetime.now(timezone.utc)
    burst_counts = _burst_counts_for_month(anchor.year, anchor.month)
    if not burst_counts and ref_date:
        ref_dt = datetime.strptime(ref_date, "%Y-%m-%d")
        burst_counts = _burst_counts_for_month(ref_dt.year, ref_dt.month)
        anchor = ref_dt
    burst_month = f"{anchor.year:04d}-{anchor.month:02d}" if burst_counts else ""

    # The catalogue is driven by real data: stations reporting now, plus every
    # station we already know coordinates for. The hand-written list is never the
    # source of truth for *which* stations exist — only a coordinate fallback.
    # Station existence comes from archive/catalog sightings. The coordinate
    # registry is only a lookup table and must never create phantom stations.
    catalog = reporting_set | _known_station_names(ref_date)

    entries: list[StationGeo] = []
    unmapped: list[str] = []
    fits_count = 0
    for name in sorted(catalog):
        operative = name in reporting_set
        coords = _resolve_station_coords(name)
        if coords is None:
            if operative:  # surface only live stations we can't place yet
                unmapped.append(name)
            continue
        if coords[2] == "fits":
            fits_count += 1
        entries.append(
            StationGeo(
                station=name,
                lat=coords[0],
                lon=coords[1],
                operative=operative,
                burst_count=burst_counts.get(name, 0),
                coord_source=coords[2],
            )
        )

    # Learn real coordinates in the background for live stations still on the
    # fallback (or unmapped), a few per call, throttled to spare the archive.
    now_ts = datetime.now(timezone.utc).timestamp()
    need = [
        e.station for e in entries if e.coord_source == "approx" and e.operative
    ] + unmapped
    todo = [
        st for st in need
        if now_ts - _COORD_ATTEMPTS.get(st, 0) > _COORD_ATTEMPT_COOLDOWN
    ][:6]
    if todo and ref_date:
        for st in todo:
            _COORD_ATTEMPTS[st] = now_ts
        _COORD_EXECUTOR.submit(_harvest_coords_by_download, todo, ref_date)

    operative_count = sum(1 for e in entries if e.operative)
    return StationsGeoResponse(
        stations=entries,
        source="ethz" if ref_date else "static",
        operative_count=operative_count,
        total_count=len(entries),
        reference_date=ref_date,
        burst_month=burst_month,
        burst_total=sum(burst_counts.values()),
        unmapped=sorted(unmapped),
        fits_coord_count=fits_count,
        retention_days=_station_retention_days(),
    )


_FILES_CACHE: dict[tuple[str, str], tuple[float, FilesResponse]] = {}
_FILES_CACHE_LOCK = threading.Lock()
_FILES_CACHE_TTL = 120.0


@app.get("/api/files", response_model=FilesResponse)
def get_files(
    station: str = Query(..., description="e-Callisto station name"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
):
    """List all burst files available for a station and date.

    Merges locally cached files (already downloaded) with those available on ETHZ.
    Each entry includes the filename and the start time extracted from its name.
    """
    try:
        station = validate_station(station)
        validate_date(date)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    cache_key = (station.upper(), date)
    now = datetime.now(timezone.utc).timestamp()
    with _FILES_CACHE_LOCK:
        cached_response = _FILES_CACHE.get(cache_key)
    if cached_response and now - cached_response[0] < _FILES_CACHE_TTL:
        return cached_response[1]

    local = set(_list_local_fits_files(station, date))
    ethz = set(_list_ethz_files(station, date))
    all_files = sorted(local | ethz)

    source = "ethz" if ethz else ("local" if local else "none")
    if local and ethz and local != ethz:
        source = "mixed"

    entries: list[FileEntry] = []
    for fn in all_files:
        t = _time_from_filename(fn)
        cached = "★ " if fn in local else ""
        entries.append(FileEntry(
            filename=fn, time=t, label=f"{cached}{t}",
            focus_code=_focus_code_from_filename(fn),
        ))

    response = FilesResponse(station=station, date=date, files=entries, source=source)
    with _FILES_CACHE_LOCK:
        _FILES_CACHE[cache_key] = (now, response)
    return response


@app.get("/api/spectrogram", response_model=SpectrogramResponse)
def get_spectrogram(
    station: str = Query(..., description="e-Callisto station, e.g. SPAIN-SIGUENZA"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    filename: str = Query(default=None, description="Specific FITS filename"),
    file_path: str | None = Query(default=None, deprecated=True, include_in_schema=False),
    sahan_filter: bool = Query(default=False, description="Apply full RFI cleaning"),
    max_time_bins: int = Query(default=None, description="Decimate time axis to at most N columns (overview mode)"),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0, description="RFI robust z-score threshold"),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0, description="RFI channel occupancy threshold"),
    rfi_min_component: int = Query(default=9, ge=1, le=500, description="Min connected-component size for impulsive RFI"),
    rfi_impulsive: bool = Query(default=True, description="Enable impulsive (connected-component) RFI stage"),
    scale_mode: str = Query(default="relative", pattern="^(relative|median_db)$"),
):
    """Return the spectrogram for an e-Callisto station.

    Resolution order (the API never accepts arbitrary filesystem paths):
    2) filename → local cache → ETHZ download
    3) first local match → NAS → ETHZ download

    Processing pipeline:
    - Always: robust background subtraction (25th percentile per frequency channel).
    - If sahan_filter=true: additionally applies RFI mitigation v2 (occupancy +
      connected components + channel-median inpainting, from Burst_No_Burst).
    - vmin/vmax are always recomputed on the processed data.
    """
    if file_path is not None:
        raise HTTPException(status_code=410, detail="file_path was removed for security; use station/date/filename")
    try:
        station = validate_station(station)
        validate_date(date)
        if filename:
            filename = validate_filename_context(filename, station, date)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    try:
        return _build_spectrogram(
            station, date,
            filename=filename,
            sahan_filter=sahan_filter,
            max_time_bins=max_time_bins,
            rfi_z_thresh=rfi_z_thresh,
            rfi_occupancy=rfi_occupancy,
            rfi_min_component=rfi_min_component,
            rfi_impulsive=rfi_impulsive,
            scale_mode=scale_mode,
        )
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error processing spectrogram for %s %s", station, date)
        raise HTTPException(status_code=500, detail="Spectrogram processing failed; use the request id to inspect server logs") from exc


@app.get("/api/spectrogram/combine", response_model=CombinedSpectrogramResponse)
async def get_spectrogram_combine(
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    stations: list[str] = Query(..., description="Station names to combine"),
    filename: str = Query(default=None, description="Primary station filename for 15-min block sync"),
    sahan_filter: bool = Query(default=False, description="Apply full RFI cleaning"),
    max_time_bins: int = Query(default=None, description="Decimate time axis to at most N columns (overview mode)"),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0),
    rfi_min_component: int = Query(default=9, ge=1, le=500),
    rfi_impulsive: bool = Query(default=True),
    scale_mode: str = Query(default="relative", pattern="^(relative|median_db)$"),
):
    """Return per-station spectrograms for multiple stations, processed concurrently.

    When `filename` is provided, the primary station (stations[0]) is fetched with
    that exact file and all secondary stations are synced to the same 15-minute block
    by scanning for a file whose HHMM matches the primary's. Stations with no matching
    file for that block are reported in `failed`.
    """
    if not stations:
        raise HTTPException(status_code=422, detail="At least one station is required.")
    try:
        validate_date(date)
        stations = [validate_station(station) for station in stations]
        if filename:
            filename = validate_filename_context(filename, stations[0], date)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    if len(stations) > _MAX_COMBINE_STATIONS:
        raise HTTPException(
            status_code=422,
            detail=f"Too many stations requested: {len(stations)} > {_MAX_COMBINE_STATIONS}.",
        )

    # Derive HHMM target for time-sync (strip colons from "HH:MM:SS" → "HHMMSS")
    target_hhmm: str | None = None
    if filename:
        raw = _time_from_filename(filename).replace(":", "")  # "HHMMSS" or "??????"
        if len(raw) >= 4 and raw[:4].isdigit():
            target_hhmm = raw[:4]

    rfi_kwargs = dict(
        rfi_z_thresh=rfi_z_thresh,
        rfi_occupancy=rfi_occupancy,
        rfi_min_component=rfi_min_component,
        rfi_impulsive=rfi_impulsive,
        scale_mode=scale_mode,
    )

    def _process_one(
        st: str,
        exact_filename: str | None,
        match_hhmm: str | None,
    ) -> tuple[str, SpectrogramResponse | None, str | None]:
        try:
            if exact_filename:
                # Primary station: use the exact file the user selected
                logger.info("combine: station=%s exact_file=%s", st, exact_filename)
                result = _build_spectrogram(
                    st, date, filename=exact_filename,
                    sahan_filter=sahan_filter, max_time_bins=max_time_bins,
                    **rfi_kwargs,
                )
            elif match_hhmm:
                # Secondary station: scan available files and pick the one matching HHMM
                local = set(_list_local_fits_files(st, date))
                ethz = set(_list_ethz_files(st, date))
                all_files = sorted(local | ethz)
                matched = next(
                    (
                        f for f in all_files
                        if _time_from_filename(f).replace(":", "")[:4] == match_hhmm
                    ),
                    None,
                )
                if matched is None:
                    raise FileNotFoundError(
                        f"No file for time block {match_hhmm[:2]}:{match_hhmm[2:]} on {date}."
                    )
                logger.info("combine: station=%s matched_file=%s", st, matched)
                result = _build_spectrogram(
                    st, date, filename=matched,
                    sahan_filter=sahan_filter, max_time_bins=max_time_bins,
                    **rfi_kwargs,
                )
            else:
                # No time anchor was derived — refuse rather than silently loading an
                # arbitrary file, which would produce unsynchronised or duplicated data.
                raise FileNotFoundError(
                    f"No time anchor for station '{st}': cannot determine which "
                    "15-minute block to load. Provide a primary filename."
                )
            return st, result, None
        except Exception as exc:
            logger.warning("combine: %s failed: %s", st, exc)
            return st, None, str(exc)

    # Primary station gets the exact filename; secondaries get HHMM sync
    tasks = [
        (st, filename if (i == 0 and filename) else None, target_hhmm if i > 0 else None)
        for i, st in enumerate(stations)
    ]

    loop = asyncio.get_event_loop()
    futures = [
        loop.run_in_executor(_COMBINE_EXECUTOR, _process_one, st, fname, hhmm)
        for st, fname, hhmm in tasks
    ]
    results = await asyncio.gather(*futures)

    layers: list[SpectrogramResponse] = []
    failed: list[dict] = []
    for st, layer, reason in results:
        if layer is not None:
            layers.append(layer)
        else:
            failed.append({"station": st, "reason": reason})

    if not layers:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for any of the requested stations on {date}.",
        )

    return CombinedSpectrogramResponse(date=date, layers=layers, failed=failed)


# ── High-resolution zoom patch ────────────────────────────────────────────────

# Zoom patches may be denser than the 1500-col overview: this ceiling only
# guards against pathological requests (e.g. full-file zoom at raw resolution).
_MAX_ZOOM_COLS = 2400


@app.get("/api/spectrogram/zoom", response_model=SpectrogramResponse)
def get_spectrogram_zoom(
    station: str = Query(..., description="e-Callisto station"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    filename: str = Query(..., description="Exact filename already shown in the overview"),
    t0: str = Query(..., description="Start time ISO-8601 UTC (from Plotly xaxis.range)"),
    t1: str = Query(..., description="End time ISO-8601 UTC (from Plotly xaxis.range)"),
    f0: float = Query(..., description="Start frequency MHz (from Plotly yaxis.range)"),
    f1: float = Query(..., description="End frequency MHz (from Plotly yaxis.range)"),
    sahan_filter: bool = Query(default=False),
    rfi_z_thresh: float = Query(default=6.0, ge=0.5, le=20.0),
    rfi_occupancy: float = Query(default=0.15, ge=0.01, le=1.0),
    rfi_min_component: int = Query(default=9, ge=1, le=500),
    rfi_impulsive: bool = Query(default=True),
    scale_mode: str = Query(default="relative", pattern="^(relative|median_db)$"),
):
    """Return a maximum-resolution patch for a time+frequency bounding box.

    Uses the raw-data LRU cache so repeated zoom requests on the same file
    do not re-parse the FITS. Background subtraction and optional RFI cleaning
    are recomputed on the slice only, so contrast is optimised for the zoomed
    region — intentional behaviour.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    # Resolve the FITS file (must already be local — overview guarantees this)
    try:
        station = validate_station(station)
        filename = validate_filename_context(filename, station, date)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    local_path = safe_join(DATA_DIR_LOCAL, filename)
    if os.path.isfile(local_path):
        fits_path = local_path
    else:
        fits_path = _download_from_ethz(station, date, filename=filename)
    if not fits_path:
        raise HTTPException(
            status_code=404,
            detail=f"File '{filename}' not found for station '{station}' on {date}.",
        )

    try:
        data_raw, freqs, time_arr, header = _load_raw_cached(fits_path)
        time_labels: list[str] = _times_to_utc(time_arr, header)

        # ── Column indices (time) ─────────────────────────────────────────────
        try:
            t0_ts = _parse_utc(t0).timestamp()
            t1_ts = _parse_utc(t1).timestamp()
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=f"Cannot parse time bounds: {exc}")
        if t0_ts > t1_ts:
            t0_ts, t1_ts = t1_ts, t0_ts

        label_ts = np.array([_parse_utc(lb).timestamp() for lb in time_labels])
        col0 = int(np.searchsorted(label_ts, t0_ts, side="left"))
        col1 = int(np.searchsorted(label_ts, t1_ts, side="right"))
        col0 = max(0, col0)
        col1 = min(data_raw.shape[1], col1)

        # ── Row indices (frequency, handle descending axis) ───────────────────
        freqs_arr = np.asarray(freqs)
        f_lo, f_hi = min(f0, f1), max(f0, f1)
        if freqs_arr.size > 1 and freqs_arr[-1] > freqs_arr[0]:
            # Ascending frequency axis
            row0 = int(np.searchsorted(freqs_arr, f_lo, side="left"))
            row1 = int(np.searchsorted(freqs_arr, f_hi, side="right"))
        else:
            # Descending: flip, searchsort, then map back to original indices
            freqs_flip = freqs_arr[::-1]
            r0 = int(np.searchsorted(freqs_flip, f_lo, side="left"))
            r1 = int(np.searchsorted(freqs_flip, f_hi, side="right"))
            n = len(freqs_arr)
            row0 = n - r1
            row1 = n - r0
        row0 = max(0, row0)
        row1 = min(data_raw.shape[0], row1)

        if col1 <= col0 or row1 <= row0:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"Zoom box is outside data range or too narrow "
                    f"(cols {col0}:{col1}, rows {row0}:{row1})."
                ),
            )

        # ── Slice ─────────────────────────────────────────────────────────────
        data_slice = data_raw[row0:row1, col0:col1]
        if scale_mode == "median_db":
            data_slice = data_slice * (2500.0 / 255.0 / 25.4)
        freqs_slice = freqs_arr[row0:row1]
        time_slice: list[str] = time_labels[col0:col1]

        # Decimate only if the slice is still very wide
        if data_slice.shape[1] > _MAX_ZOOM_COLS:
            data_slice, time_slice = _decimate_time(data_slice, time_slice, _MAX_ZOOM_COLS)

        # ── Process on the slice ──────────────────────────────────────────────
        data_proc = _subtract_background(data_slice)
        rfi_masked: list[int] = []
        rfi_stats: dict = {}
        if sahan_filter:
            data_proc, rfi_masked, rfi_stats = _mitigate_rfi(
                data_proc,
                z_thresh=rfi_z_thresh,
                occupancy_thresh=rfi_occupancy,
                min_component_size=rfi_min_component,
                impulsive=rfi_impulsive,
            )

        finite_vals = data_proc[np.isfinite(data_proc)]
        if finite_vals.size == 0:
            vmin, vmax = 0.0, 1.0
        else:
            vmin, vmax = _percentile_clip_global(data_proc.astype(float))

        data_out = np.nan_to_num(
            np.array(data_proc, dtype=float),
            nan=0.0,
            posinf=vmax,
            neginf=vmin,
        )

        return SpectrogramResponse(
            station=station,
            date=date,
            filename=filename,
            time_axis=time_slice,
            freq_axis=np.round(np.asarray(freqs_slice, dtype=float), 3).tolist(),
            z=np.round(data_out, 4).tolist(),
            vmin=round(vmin, 4),
            vmax=round(vmax, 4),
            fits_header=_header_to_dict(header),
            rfi_masked_channels=rfi_masked,
            rfi_stats=rfi_stats,
            unit="dB" if scale_mode == "median_db" else "relative digits",
            scale_mode=scale_mode,
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Zoom failed for %s %s: %s", station, filename, exc)
        raise HTTPException(status_code=500, detail="Zoom processing failed; use the request id to inspect server logs") from exc


# ── Automatic burst detection (CNN+MIL from Burst_No_Burst by Sahan) ─────────

# Single worker: CPU inference is heavy and the model bundle is a shared
# singleton — serialising requests avoids thrashing.
_BURST_EXECUTOR = ThreadPoolExecutor(max_workers=1, thread_name_prefix="burst")


@app.get("/api/burst/detect", response_model=BurstDetectResponse)
async def detect_burst(
    station: str = Query(..., description="e-Callisto station"),
    date: str = Query(..., description="Observation date, format YYYY-MM-DD"),
    filename: str = Query(..., description="Exact FITS filename (as shown in the overview)"),
):
    """Run the trained CNN+MIL burst classifier on one FITS file.

    Ported from Burst_No_Burst by Sahan: model-specific preprocessing
    (log1p → running-quantile baseline → per-frequency normalisation → RFI
    mitigation → clipping), 128×128 windowing, window CNN scoring and MIL
    bag pooling. Returns the file-level burst probability, the calibrated
    threshold and the candidate event intervals (time + frequency band).

    ONNX Runtime is optional: when it or the model bundle is unavailable, the
    endpoint answers with ``available=false`` and a reason instead of failing.
    """
    try:
        station = validate_station(station)
        validate_date(date)
        filename = validate_filename_context(filename, station, date)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    from backend import burst_detect  # deferred: inference runtime stays optional

    ok, reason = burst_detect.is_available()
    if not ok:
        return BurstDetectResponse(
            station=station, date=date, filename=filename,
            available=False, reason=reason,
        )

    # Resolve the FITS file (usually already local — the overview loaded it)
    local_path = safe_join(DATA_DIR_LOCAL, filename)
    if os.path.isfile(local_path):
        fits_path = local_path
    else:
        fits_path = _download_from_ethz(station, date, filename=filename)
    if not fits_path:
        raise HTTPException(
            status_code=404,
            detail=f"File '{filename}' not found for station '{station}' on {date}.",
        )

    def _run() -> dict:
        data_raw, freqs, time_arr, header = _load_raw_cached(fits_path)
        time_s = _time_offsets_seconds(time_arr, header)
        obs_start = _observation_start(header)
        return burst_detect.detect_bursts(data_raw, freqs, time_s, obs_start)

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(_BURST_EXECUTOR, _run)
    except Exception as exc:
        logger.exception("Burst detection failed for %s: %s", filename, exc)
        raise HTTPException(status_code=500, detail="Burst detection failed; use the request id to inspect server logs") from exc

    logger.info(
        "Burst detection %s: score=%.3f (threshold %.2f), %d event(s), %.0f ms",
        filename, result["file_score"], result["threshold"],
        len(result["events"]), result["inference_ms"],
    )
    return BurstDetectResponse(
        station=station, date=date, filename=filename,
        available=True, **result,
    )


# ── GOES/XRS overlay (ported from goes_overlay.py by Sahan, simplified) ──────

_GOES_CACHE_DIR = os.path.join(DATA_DIR_LOCAL, "goes_cache")
_GOES_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="goes-fido")

# Preferred GOES satellite order by epoch (from goes_overlay.py by Sahan).
def _preferred_goes_satellites(year: int) -> tuple[int, ...]:
    if year >= 2025:
        return (19, 18, 17, 16)
    if year >= 2022:
        return (18, 17, 16, 15, 14, 13)
    if year >= 2017:
        return (17, 16, 15, 14, 13)
    if year >= 2010:
        return (15, 14, 13, 12, 11, 10)
    if year >= 2003:
        return (12, 11, 10, 9, 8)
    if year >= 1997:
        return (10, 9, 8)
    return (9, 8)


def _pick_xrsb_column(columns: list[str]) -> str | None:
    """Select the XRS-B column (long channel, 0.1–0.8 nm) by heuristic scoring.

    Ported from goes_overlay._goes_channel_score() by Sahan.
    """
    best, best_score = None, -10_000
    for col in columns:
        lowered = str(col).strip().lower()
        if not lowered:
            continue
        score = 0
        if lowered == "xrsb_flux":
            score += 160
        if lowered == "b_flux":
            score += 150
        if any(tok in lowered for tok in ("xrsb", "long", "1.0", "8.0")):
            score += 60
        if lowered.startswith("b_"):
            score += 15
        if "flux" in lowered:
            score += 80
        if lowered.endswith("_flux"):
            score += 20
        if any(tok in lowered for tok in ("flag", "quality", "count", "num", "primary", "excluded")):
            score -= 220
        if any(tok in lowered for tok in ("electron", "current")):
            score -= 160
        if score > best_score:
            best, best_score = str(col), score
    return best if best_score > 0 else None


def _fetch_goes_xrsb_sync(date_str: str) -> dict:
    """Download GOES XRS-B data via sunpy.net.Fido for a full UTC day.

    Returns {"times": [...iso8601], "xrsb": [...W/m²], "satellite": int}.
    """
    try:
        from sunpy import timeseries as ts
        from sunpy.net import Fido
        from sunpy.net import attrs as a
    except ImportError as exc:
        raise RuntimeError(
            f"sunpy is not installed in the backend ({exc}). "
            "Install with: pip install 'sunpy[net,timeseries]'"
        )

    target = datetime.strptime(date_str, "%Y-%m-%d")
    start = target.strftime("%Y-%m-%d 00:00:00")
    end = target.strftime("%Y-%m-%d 23:59:59")
    os.makedirs(_GOES_CACHE_DIR, exist_ok=True)

    sats = _preferred_goes_satellites(target.year)
    last_err: Exception | None = None

    for sat in sats:
        try:
            logger.info("Searching GOES-%d XRS for %s in SunPy archive…", sat, date_str)
            try:
                query = Fido.search(
                    a.Time(start, end),
                    a.Instrument.xrs,
                    a.goes.SatelliteNumber(sat),
                )
            except AttributeError:
                # Older alternative API
                query = Fido.search(
                    a.Time(start, end),
                    a.Instrument("XRS"),
                    a.goes.SatelliteNumber(sat),
                )
            if len(query) == 0 or sum(len(t) for t in query) == 0:
                continue

            paths = Fido.fetch(query, path=os.path.join(_GOES_CACHE_DIR, "{file}"))
            if len(paths) == 0:
                continue

            tseries = ts.TimeSeries(list(paths), concatenate=True)
            df = tseries.to_dataframe()
            numeric_cols = [c for c in df.columns if np.issubdtype(df[c].dtype, np.number)]
            if not numeric_cols:
                continue

            col_b = _pick_xrsb_column(numeric_cols) or numeric_cols[-1]
            flux = np.asarray(df[col_b].values, dtype=float)

            idx = df.index
            times_py = idx.to_pydatetime() if hasattr(idx, "to_pydatetime") else list(idx)

            out_times: list[str] = []
            out_flux: list[float] = []
            for t, f in zip(times_py, flux, strict=False):
                if not np.isfinite(f) or f <= 0.0:
                    continue
                if hasattr(t, "tzinfo") and t.tzinfo is None:
                    t = t.replace(tzinfo=timezone.utc)
                if not (target.date() == t.date() if hasattr(t, "date") else True):
                    continue
                ms = t.microsecond // 1000 if hasattr(t, "microsecond") else 0
                out_times.append(f"{t.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z")
                out_flux.append(float(f))

            if out_times:
                logger.info("GOES-%d XRS: %d valid samples", sat, len(out_times))
                return {"times": out_times, "xrsb": out_flux, "satellite": sat}
        except Exception as exc:
            logger.debug("GOES-%d failed: %s", sat, exc)
            last_err = exc
            continue

    raise RuntimeError(
        f"No GOES/XRS data found for {date_str}"
        + (f" ({last_err})" if last_err else "")
    )


@app.get("/api/goes", response_model=GoesResponse)
async def get_goes(date: str = Query(..., description="Date YYYY-MM-DD")):
    """Return GOES XRS-B flux (0.1–0.8 nm channel) for a full UTC day.

    Source: SunPy/Fido archive (NOAA NGDC / NCEI). Covers from approximately
    1986 onwards across all GOES satellite generations.
    """
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid date format: '{date}'")

    try:
        with session_scope() as session:
            cached_day = session.get(GoesDay, date)
            if cached_day:
                return GoesResponse(**cached_day.payload)
    except Exception as exc:
        logger.debug("Database GOES cache unavailable: %s", exc)

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(_GOES_EXECUTOR, _fetch_goes_xrsb_sync, date)
    except Exception as exc:
        logger.warning("GOES not available for %s: %s", date, exc)
        return GoesResponse(
            date=date,
            available=False,
            reason=str(exc),
            times=[],
            xrsb=[],
            satellite=None,
        )

    response = GoesResponse(
        date=date,
        available=True,
        reason="",
        times=result["times"],
        xrsb=result["xrsb"],
        satellite=result.get("satellite"),
    )
    try:
        with session_scope() as session:
            session.merge(GoesDay(date=date, payload=response.model_dump()))
    except Exception as exc:
        logger.debug("Could not persist GOES cache: %s", exc)
    return response


# uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000


def _mount_frontend() -> None:
    """Serve the production Vite build from the API in single-host deployments."""
    if os.environ.get("SERVE_FRONTEND", "").strip().lower() not in {"1", "true", "yes"}:
        return
    dist_dir = os.path.realpath(os.environ.get("FRONTEND_DIST_DIR", "frontend/dist"))
    if not os.path.isfile(os.path.join(dist_dir, "index.html")):
        logger.warning("SERVE_FRONTEND enabled but no index.html exists in %s", dist_dir)
        return
    app.mount("/", StaticFiles(directory=dist_dir, html=True), name="frontend")
    logger.info("Serving the AstroDoncel frontend from %s", dist_dir)


_mount_frontend()
